create table if not exists public.aura_tester_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  sender text not null check (sender in ('user','tester')),
  content text not null check (char_length(content) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists aura_tester_messages_user_idx on public.aura_tester_messages(user_id,created_at);
alter table public.aura_tester_messages enable row level security;
drop policy if exists "Usuário vê conversa com Aura Tester" on public.aura_tester_messages;
create policy "Usuário vê conversa com Aura Tester" on public.aura_tester_messages for select to authenticated using ((select auth.uid())=user_id);
grant select on public.aura_tester_messages to authenticated;
create or replace function public.send_aura_tester_message(p_content text) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid:=auth.uid();v_text text:=trim(p_content);v_reply text;
begin
 if v_user is null then raise exception 'Sessão necessária';end if;
 if char_length(v_text)<1 or char_length(v_text)>1000 then raise exception 'Mensagem inválida';end if;
 insert into public.aura_tester_messages(user_id,sender,content)values(v_user,'user',v_text);
 v_reply:=case when v_text~*'(oi|olá|ola|bom dia|boa tarde|boa noite)' then 'Olá! Eu sou o Aura Tester. Estou aqui para você experimentar as conversas da comunidade. ✦' when v_text~*'(ponto|xp|aura)' then 'Seus pontos crescem quando você conclui ações. Abra Atividade para escolher o próximo passo.' when v_text~*'(projeto|ideia)' then 'Uma ideia fica mais leve quando ganha um próximo passo. Que pequena ação você consegue fazer agora?' when v_text~*'(ajuda|como)' then 'Experimente perguntar sobre pontos, projetos ou atividades.' else 'Recebi sua mensagem! Esta experiência será usada também nas conversas entre pessoas.' end;
 insert into public.aura_tester_messages(user_id,sender,content)values(v_user,'tester',v_reply);
end;$$;
revoke all on function public.send_aura_tester_message(text) from public,anon;grant execute on function public.send_aura_tester_message(text) to authenticated;
