-- Aura 67: catálogo de hábitos, conclusões e XP seguro.
-- Execute no ambiente de teste depois da migration 003.

create table if not exists public.actions_catalog (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category text not null check (category in ('health','mental','home','finance','productivity','social','special')),
  title text not null,
  description text,
  icon text not null default '✦',
  xp integer not null check (xp between 1 and 100),
  difficulty text not null default 'easy' check (difficulty in ('easy','medium','hard','special')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.action_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  action_id bigint not null references public.actions_catalog(id),
  completed_on date not null default (timezone('America/Sao_Paulo', now()))::date,
  base_xp integer not null,
  bonus_xp integer not null default 0,
  created_at timestamptz not null default now(),
  unique (user_id, action_id, completed_on)
);

alter table public.actions_catalog enable row level security;
alter table public.action_completions enable row level security;
create policy "Catálogo ativo é público" on public.actions_catalog for select to anon, authenticated using (active = true);
create policy "Usuário vê suas conclusões" on public.action_completions for select to authenticated using ((select auth.uid()) = user_id);
grant select on public.actions_catalog to anon, authenticated;
grant select on public.action_completions to authenticated;

insert into public.actions_catalog (slug,category,title,description,icon,xp,difficulty) values
('drink-2l-water','health','Beber 2L de água','Complete sua meta de hidratação do dia.','💧',15,'medium'),
('eat-breakfast','health','Tomar café da manhã','Comece o dia com energia.','🥣',5,'easy'),
('eat-fruit','health','Comer 1 fruta','Inclua uma fruta no seu dia.','🍎',5,'easy'),
('eat-salad','health','Comer uma salada','Adicione vegetais a uma refeição.','🥗',10,'easy'),
('walk-15','health','Caminhar 15 minutos','Movimente o corpo por pelo menos 15 minutos.','🚶',15,'medium'),
('pushups-10','health','Fazer 10 flexões','Complete dez flexões no seu ritmo.','💪',15,'medium'),
('stretch-5','health','Alongar por 5 minutos','Cuide da mobilidade e respiração.','🧘',10,'easy'),
('sleep-early','health','Dormir no horário planejado','Respeite o horário definido para descansar.','🌙',20,'medium'),
('less-phone','health','Passar menos tempo no celular','Fique abaixo da sua meta diária de tela.','📵',20,'hard'),
('take-shower','health','Tomar banho','Faça seu cuidado básico do dia.','🚿',5,'easy'),
('brush-3','health','Escovar os dentes 3x','Complete os três cuidados do dia.','🪥',10,'easy'),
('no-soda','health','Evitar refrigerante hoje','Passe o dia sem refrigerante.','🥤',15,'medium'),
('read-5','mental','Ler 5 páginas','Avance pelo menos cinco páginas.','📖',10,'easy'),
('no-phone-10','mental','Ficar 10 minutos sem celular','Faça uma pausa consciente das telas.','🧠',10,'easy'),
('meditate-5','mental','Meditar por 5 minutos','Respire e observe o presente.','🪷',10,'easy'),
('three-good-things','mental','Escrever 3 coisas boas do dia','Registre três momentos positivos.','✍️',15,'medium'),
('plan-tomorrow','mental','Planejar o dia seguinte','Defina prioridades para amanhã.','🗓️',10,'easy'),
('do-delayed','mental','Fazer algo que estava adiando','Dê um passo real em algo pendente.','⚡',30,'hard'),
('learn-new','mental','Aprender uma coisa nova','Registre um novo aprendizado.','💡',15,'medium'),
('educational-podcast','mental','Ouvir um podcast educativo','Aprenda enquanto escuta.','🎧',15,'medium'),
('no-social-30','mental','Ficar 30 minutos sem redes sociais','Crie espaço mental sem feeds.','🌿',15,'medium'),
('make-bed','home','Arrumar a cama','Comece organizando seu espaço.','🛏️',5,'easy'),
('wash-dishes','home','Lavar a louça','Deixe a pia organizada.','🍽️',10,'easy'),
('organize-desk','home','Organizar a mesa','Prepare um ambiente mais leve.','🧹',10,'easy'),
('put-clothes-away','home','Guardar roupas','Coloque as roupas em seus lugares.','👕',10,'easy'),
('clean-room-10','home','Limpar o quarto por 10 minutos','Faça uma limpeza curta e focada.','✨',15,'medium'),
('discard-five','home','Jogar 5 coisas fora','Retire cinco itens sem utilidade.','♻️',10,'easy'),
('organize-drawer','home','Organizar uma gaveta','Escolha uma gaveta e conclua.','🗄️',15,'medium'),
('clean-device','home','Limpar o computador ou celular','Cuide do dispositivo por dentro ou por fora.','💻',10,'easy'),
('prepare-clothes','home','Separar roupas para amanhã','Deixe a próxima manhã mais simples.','🧥',5,'easy'),
('no-unnecessary-spend','finance','Não gastar com algo desnecessário','Evite uma compra por impulso hoje.','🛡️',20,'hard'),
('save-five','finance','Guardar R$ 5','Separe cinco reais para seu futuro.','💰',10,'easy'),
('log-expenses','finance','Anotar todos os gastos do dia','Registre cada gasto realizado.','🧾',15,'medium'),
('check-bank','finance','Conferir a conta bancária','Revise saldo e movimentações.','🏦',5,'easy'),
('cancel-subscription','finance','Cancelar uma assinatura sem uso','Elimine um gasto recorrente desnecessário.','✂️',30,'hard'),
('research-purchase','finance','Pesquisar antes de comprar','Compare preços e necessidade.','🔎',10,'easy'),
('sell-unused','finance','Vender algo que não usa','Coloque um item parado à venda.','🏷️',30,'hard'),
('earn-extra-ten','finance','Fazer R$ 10 de renda extra','Crie uma pequena renda além do habitual.','📈',30,'hard'),
('delayed-task','productivity','Fazer uma tarefa adiada','Conclua uma pendência que vem evitando.','🚀',30,'hard'),
('focus-25','productivity','Trabalhar 25 minutos sem distração','Complete um ciclo de foco.','⏱️',20,'medium'),
('important-message','productivity','Responder uma mensagem importante','Não deixe uma conversa necessária parada.','💬',10,'easy'),
('resolve-pending','productivity','Resolver uma pendência','Feche um pequeno ciclo aberto.','✅',20,'medium'),
('organize-agenda','productivity','Organizar a agenda','Revise compromissos e prioridades.','📅',10,'easy'),
('start-project','productivity','Começar aquele projeto parado','Dê o primeiro passo concreto.','🌱',30,'hard'),
('task-before-game','productivity','Terminar uma tarefa antes de jogar','Transforme lazer em recompensa.','🎮',15,'medium'),
('hardest-first','productivity','Fazer primeiro a tarefa mais difícil','Enfrente sua prioridade principal.','🔥',30,'hard'),
('personal-goal-30','productivity','Trabalhar 30 minutos em um objetivo pessoal','Invista meia hora no que importa.','🎯',25,'hard'),
('message-loved-one','social','Mandar mensagem para alguém querido','Demonstre que lembrou dessa pessoa.','💌',10,'easy'),
('call-family','social','Ligar para um familiar','Crie uma conversa de verdade.','📞',15,'medium'),
('sincere-compliment','social','Fazer um elogio sincero','Reconheça algo bom em alguém.','🌟',10,'easy'),
('help-someone','social','Ajudar alguém','Ofereça ajuda de forma concreta.','🤝',20,'medium'),
('meet-person','social','Conhecer uma pessoa nova','Inicie uma nova conexão.','👋',20,'medium'),
('thank-someone','social','Agradecer alguém','Expresse gratidão de maneira clara.','🙏',10,'easy'),
('kindness','social','Fazer uma gentileza sem esperar nada','Espalhe energia positiva livremente.','💜',25,'hard'),
('flash-mission','special','Missão relâmpago','Faça algo útil nos próximos 5 minutos.','⚡',20,'special'),
('anti-laziness','special','Missão anti-preguiça','Faça por 10 minutos algo que está adiando.','🔥',30,'special')
on conflict (slug) do update set category=excluded.category,title=excluded.title,description=excluded.description,icon=excluded.icon,xp=excluded.xp,difficulty=excluded.difficulty,active=true;

create or replace function public.complete_aura_action(p_action_id bigint)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_user uuid := auth.uid(); v_action public.actions_catalog%rowtype; v_today date := (timezone('America/Sao_Paulo', now()))::date;
  v_count integer; v_bonus integer := 0; v_total bigint; v_streak integer := 0; v_day date := v_today;
begin
  if v_user is null then raise exception 'Sessão necessária'; end if;
  select * into v_action from public.actions_catalog where id=p_action_id and active=true;
  if not found then raise exception 'Ação não encontrada'; end if;
  select count(*) into v_count from public.action_completions where user_id=v_user and completed_on=v_today;
  if (v_count + 1) % 3 = 0 then v_bonus := 15; end if;
  insert into public.action_completions(user_id,action_id,completed_on,base_xp,bonus_xp) values(v_user,p_action_id,v_today,v_action.xp,v_bonus);
  update public.profiles set aura_points=aura_points+v_action.xp+v_bonus,updated_at=now() where id=v_user returning aura_points into v_total;
  while exists(select 1 from public.action_completions where user_id=v_user and completed_on=v_day) loop v_streak:=v_streak+1; v_day:=v_day-1; end loop;
  return jsonb_build_object('earned_xp',v_action.xp,'bonus_xp',v_bonus,'total_points',v_total,'today_count',v_count+1,'streak',v_streak);
exception when unique_violation then raise exception 'Você já concluiu esta ação hoje';
end; $$;
revoke all on function public.complete_aura_action(bigint) from public, anon;
grant execute on function public.complete_aura_action(bigint) to authenticated;
