let adminSession;
let proofQueue = [];
let selectedProof;
let activeProofFilter = 'pending';

function adminInitials(name='Super Admin'){return name.split(/\s+/).slice(0,2).map((part)=>part[0]).join('').toUpperCase();}
function adminEscape(value=''){const node=document.createElement('span');node.textContent=value;return node.innerHTML;}
function formatAdminDate(value){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(value));}

async function initializeAdmin(){
 if(!window.auraSupabase){showDenied();return;}
 const{data}=await window.auraSupabase.auth.getSession();adminSession=data.session;if(!adminSession){location.replace('login.html?next=admin');return;}
 const{data:allowed,error}=await window.auraSupabase.rpc('is_aura_admin');if(error||!allowed){showDenied();return;}
 const name=adminSession.user.user_metadata?.full_name||adminSession.user.email.split('@')[0];
 document.querySelector('#adminName').textContent=name;document.querySelector('#adminEmail').textContent=adminSession.user.email;document.querySelector('#adminInitials').textContent=adminInitials(name);
 document.querySelector('#adminLoading').hidden=true;document.querySelector('#adminShell').hidden=false;await Promise.all([loadMetrics(),loadProofQueue()]);
}
function showDenied(){document.querySelector('#adminLoading').hidden=true;document.querySelector('#adminDenied').hidden=false;}
async function loadMetrics(){const{data,error}=await window.auraSupabase.rpc('admin_moderation_metrics');if(error)return;document.querySelector('#metricPending').textContent=data.pending||0;document.querySelector('#navPending').textContent=data.pending||0;document.querySelector('#metricApproved').textContent=data.approved_today||0;document.querySelector('#metricRejected').textContent=data.rejected_today||0;document.querySelector('#metricMembers').textContent=data.members||0;}
async function loadProofQueue(){const container=document.querySelector('#proofQueue');container.innerHTML='<div class="queue-empty">Atualizando fila segura…</div>';const{data,error}=await window.auraSupabase.rpc('admin_proof_queue',{p_status:activeProofFilter,p_limit:100,p_offset:0});if(error){container.innerHTML=`<div class="queue-empty">${adminEscape(error.message)}</div>`;return;}proofQueue=data||[];renderProofQueue();}
function renderProofQueue(){const container=document.querySelector('#proofQueue');if(!proofQueue.length){container.innerHTML='<div class="queue-empty">Nenhuma comprovação neste filtro.</div>';return;}container.innerHTML=proofQueue.map((proof,index)=>`<article class="proof-row"><span>${adminEscape(proof.action_icon)}</span><span><strong>${adminEscape(proof.action_title)}</strong><small>${formatAdminDate(proof.submitted_at)} · +${proof.xp} XP</small></span><span><strong>${adminEscape(proof.user_name)}</strong><small>@${adminEscape(proof.username||'sem-username')} · membro #${proof.member_number||'—'}</small></span><span class="status ${proof.status}">${proof.status==='pending'?'Pendente':proof.status==='approved'?'Aprovada':'Rejeitada'}</span><button data-review-index="${index}">${proof.status==='pending'?'Analisar prova':'Visualizar'}</button></article>`).join('');container.querySelectorAll('[data-review-index]').forEach((button)=>button.addEventListener('click',()=>openReview(proofQueue[Number(button.dataset.reviewIndex)])));}
async function openReview(proof){selectedProof=proof;document.querySelector('#reviewBackdrop').hidden=false;document.body.style.overflow='hidden';document.querySelector('#reviewAction').textContent=proof.action_title;document.querySelector('#reviewUser').textContent=proof.user_name;document.querySelector('#reviewMeta').textContent=`@${proof.username||'sem-username'} · membro #${proof.member_number||'—'} · ${formatAdminDate(proof.submitted_at)}`;document.querySelector('#reviewAvatar').textContent=adminInitials(proof.user_name);document.querySelector('#reviewXp').textContent=`+${proof.xp} XP`;document.querySelector('#reviewUserNote').textContent=proof.note||'Nenhuma observação enviada.';document.querySelector('#reviewerNote').value='';document.querySelector('#reviewMessage').textContent='';document.querySelector('#approveProof').hidden=proof.status!=='pending';document.querySelector('#rejectProof').hidden=proof.status!=='pending';const image=document.querySelector('#reviewImage');image.removeAttribute('src');document.querySelector('#imageLoading').hidden=false;const{data,error}=await window.auraSupabase.storage.from('action-proofs').createSignedUrl(proof.evidence_path,300);if(error){document.querySelector('#imageLoading').textContent='Não foi possível abrir a imagem privada.';return;}image.onload=()=>{document.querySelector('#imageLoading').hidden=true;};image.src=data.signedUrl;}
function closeReview(){document.querySelector('#reviewBackdrop').hidden=true;document.body.style.overflow='';selectedProof=null;}
async function decideProof(approve){if(!selectedProof)return;const note=document.querySelector('#reviewerNote').value.trim();const message=document.querySelector('#reviewMessage');if(!approve&&!note){message.textContent='Explique o motivo da rejeição para orientar o membro.';return;}const approveButton=document.querySelector('#approveProof');const rejectButton=document.querySelector('#rejectProof');approveButton.disabled=true;rejectButton.disabled=true;message.style.color='#aeb7c5';message.textContent=approve?'Concedendo XP com segurança…':'Registrando rejeição…';const{data,error}=await window.auraSupabase.rpc('review_action_proof',{p_proof_id:selectedProof.proof_id,p_approve:approve,p_reviewer_note:note||null});approveButton.disabled=false;rejectButton.disabled=false;if(error){message.style.color='var(--red)';message.textContent=error.message;return;}message.style.color='var(--green)';message.textContent=approve?`Aprovada: +${data.earned_xp+(data.bonus_xp||0)} XP concedidos.`:'Comprovação rejeitada e motivo registrado.';setTimeout(async()=>{closeReview();await Promise.all([loadMetrics(),loadProofQueue()]);},950);}

document.querySelectorAll('[data-proof-filter]').forEach((button)=>button.addEventListener('click',()=>{document.querySelectorAll('[data-proof-filter]').forEach((item)=>item.classList.toggle('active',item===button));activeProofFilter=button.dataset.proofFilter;loadProofQueue();}));
document.querySelector('#reviewClose').addEventListener('click',closeReview);document.querySelector('#reviewBackdrop').addEventListener('click',(event)=>{if(event.target.id==='reviewBackdrop')closeReview();});document.querySelector('#approveProof').addEventListener('click',()=>decideProof(true));document.querySelector('#rejectProof').addEventListener('click',()=>decideProof(false));document.querySelector('#adminLogout').addEventListener('click',async()=>{await window.auraSupabase.auth.signOut();location.replace('login.html');});
initializeAdmin();
