let activeBehaviorPlan=null;
let behaviorActions=[];
const behaviorToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const behaviorEscape=(value='')=>{const node=document.createElement('span');node.textContent=value;return node.innerHTML};
function openBehaviorEditor(){const modal=document.querySelector('#behaviorBackdrop');document.querySelector('#behaviorAction').innerHTML=behaviorActions.map(action=>`<option value="${action.id}">${behaviorEscape(action.icon)} ${behaviorEscape(action.title)}</option>`).join('');if(activeBehaviorPlan){document.querySelector('#behaviorAction').value=activeBehaviorPlan.action_id;document.querySelector('#behaviorIdentity').value=activeBehaviorPlan.identity_label;document.querySelector('#behaviorAnchor').value=activeBehaviorPlan.anchor_text;document.querySelector('#behaviorMinimum').value=activeBehaviorPlan.minimum_version;document.querySelector('#behaviorObstacle').value=activeBehaviorPlan.obstacle_plan||''}modal.hidden=false;document.body.style.overflow='hidden'}
function closeBehaviorEditor(){document.querySelector('#behaviorBackdrop').hidden=true;document.body.style.overflow=''}
function renderNextVictory(checkins=[]){const root=document.querySelector('#nextVictory');if(!activeBehaviorPlan){const easy=behaviorActions.find(action=>action.difficulty==='easy')||behaviorActions[0];root.innerHTML=`<div class="victory-symbol">✦</div><div class="victory-copy"><span class="section-kicker">SUA PRÓXIMA PEQUENA VITÓRIA</span><h2 id="nextVictoryTitle">Comece pequeno. Continue sendo você.</h2><p>${easy?`Uma boa primeira opção é <strong>${behaviorEscape(easy.title)}</strong>. Escolha quando ela cabe no seu dia.`:'Crie um plano simples ligado a um momento real da sua rotina.'}</p></div><button class="primary-button" id="configureBehavior" type="button">Criar meu plano</button>`;document.querySelector('#configureBehavior').addEventListener('click',openBehaviorEditor);return}
  const today=behaviorToday(),doneToday=checkins.some(item=>item.checkin_on===today),created=new Date(activeBehaviorPlan.created_at),days=Math.max(1,Math.min(30,Math.floor((Date.now()-created.getTime())/86400000)+1)),consistency=Math.round(new Set(checkins.map(item=>item.checkin_on)).size/days*100);const prior=checkins.some(item=>item.checkin_on<today);const recovery=prior&&!doneToday&&consistency<100;
  root.innerHTML=`<div class="victory-main"><div class="victory-icon">${behaviorEscape(activeBehaviorPlan.actions_catalog.icon)}</div><div class="victory-copy"><span class="section-kicker">${doneToday?'VITÓRIA DE HOJE REGISTRADA':recovery?'UM NOVO COMEÇO CONTA':'SUA PRÓXIMA PEQUENA VITÓRIA'}</span><h2 id="nextVictoryTitle">${doneToday?'Você apareceu por você hoje.':behaviorEscape(activeBehaviorPlan.actions_catalog.title)}</h2><p><b>Depois de ${behaviorEscape(activeBehaviorPlan.anchor_text)}</b>, eu vou ${behaviorEscape(activeBehaviorPlan.actions_catalog.title.toLowerCase())}.</p><small>Identidade em construção: ${behaviorEscape(activeBehaviorPlan.identity_label)}</small></div></div><div class="victory-side"><div class="consistency-ring" style="--consistency:${consistency*3.6}deg"><strong>${consistency}%</strong><small>consistência</small></div>${doneToday?'<button class="victory-edit" id="editBehavior" type="button">Ajustar plano</button>':`<button class="primary-button" id="doVictory" type="button">Fazer agora</button><button class="minimum-button" id="minimumVictory" type="button">Hoje farei o mínimo</button><button class="victory-edit" id="editBehavior" type="button">Ajustar plano</button>`}</div>`;
  document.querySelector('#editBehavior').addEventListener('click',openBehaviorEditor);document.querySelector('#doVictory')?.addEventListener('click',()=>{if(typeof completeHabit==='function')completeHabit(Number(activeBehaviorPlan.action_id))});document.querySelector('#minimumVictory')?.addEventListener('click',completeMinimumVictory);
}
async function loadBehaviorJourney(){if(!window.AURA_SESSION||!window.auraSupabase)return;const[{data:actions,error:actionError},{data:plans,error:planError}]=await Promise.all([window.auraSupabase.from('actions_catalog').select('id,title,description,icon,difficulty,proof_mode').eq('active',true).order('xp'),window.auraSupabase.from('behavior_plans').select('*,actions_catalog(id,title,description,icon,difficulty,proof_mode)').eq('active',true).maybeSingle()]);if(actionError)return;behaviorActions=actions||[];if(planError){document.querySelector('#nextVictory').innerHTML='<div class="victory-loading">Execute a migration 015 para ativar sua jornada comportamental.</div>';return}activeBehaviorPlan=plans||null;let checkins=[];if(activeBehaviorPlan){const since=new Date();since.setDate(since.getDate()-29);const{data}=await window.auraSupabase.from('behavior_checkins').select('checkin_on,mode').gte('checkin_on',since.toISOString().slice(0,10)).order('checkin_on',{ascending:false});checkins=data||[]}renderNextVictory(checkins)}
async function completeMinimumVictory(){if(!activeBehaviorPlan)return;const button=document.querySelector('#minimumVictory');button.disabled=true;const{data,error}=await window.auraSupabase.rpc('complete_behavior_minimum',{p_plan_id:activeBehaviorPlan.id});if(error){button.disabled=false;showToast(error.message,'error','Não foi possível registrar');return}showToast(`${activeBehaviorPlan.minimum_version}. +${data.earned_points} pontos por manter o vínculo. `,'success','O mínimo também conta');await loadBehaviorJourney();if(typeof loadProfile==='function')loadProfile(window.AURA_SESSION)}
document.querySelector('#behaviorForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;const{error}=await window.auraSupabase.rpc('save_behavior_plan',{p_action_id:Number(document.querySelector('#behaviorAction').value),p_identity_label:document.querySelector('#behaviorIdentity').value.trim(),p_anchor_text:document.querySelector('#behaviorAnchor').value.trim(),p_minimum_version:document.querySelector('#behaviorMinimum').value.trim(),p_obstacle_plan:document.querySelector('#behaviorObstacle').value.trim()||null});button.disabled=false;if(error){showToast(error.message,'error','Não foi possível salvar');return}closeBehaviorEditor();showToast('Sua próxima vitória já está conectada à sua rotina.','success','Plano criado');await loadBehaviorJourney()});
document.querySelector('#behaviorClose').addEventListener('click',closeBehaviorEditor);document.querySelector('#behaviorBackdrop').addEventListener('click',event=>{if(event.target.id==='behaviorBackdrop')closeBehaviorEditor()});
document.addEventListener('aura:action-completed',async event=>{if(!activeBehaviorPlan||Number(event.detail.actionId)!==Number(activeBehaviorPlan.action_id))return;await window.auraSupabase.rpc('record_behavior_full',{p_plan_id:activeBehaviorPlan.id});loadBehaviorJourney()});
document.addEventListener('aura:session-ready',loadBehaviorJourney);if(window.AURA_SESSION)loadBehaviorJourney();
