const chatMessages=document.querySelector('#chatMessages'),chatFile=document.querySelector('#chatFile'),chatPreview=document.querySelector('#chatAttachmentPreview');
let selectedChatFile=null,chatPreviewUrl='';
const chatEscape=(value='')=>{const node=document.createElement('span');node.textContent=value;return node.innerHTML};
const chatSize=bytes=>bytes<1048576?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
async function privateAttachmentUrl(path){const{data,error}=await window.auraSupabase.storage.from('chat-attachments').createSignedUrl(path,300);return error?'':data.signedUrl}
async function renderChat(messages){chatMessages.innerHTML=messages.length?messages.map(message=>{const attachment=Array.isArray(message.chat_attachments)?message.chat_attachments[0]:message.chat_attachments;return`<article class="chat-message ${message.sender==='user'?'user':'tester'}" data-message-id="${message.id}">${attachment?attachment.mime_type.startsWith('image/')?`<button class="chat-private-image" data-private-path="${chatEscape(attachment.storage_path)}" type="button"><span>Carregando foto privada…</span></button>`:`<button class="chat-private-file" data-private-path="${chatEscape(attachment.storage_path)}" type="button"><b>PDF</b><span><strong>${chatEscape(attachment.original_name)}</strong><small>${chatSize(attachment.size_bytes)} · link temporário</small></span></button>`:''}<div class="chat-bubble-shell"><div class="chat-bubble">${chatEscape(message.content)}</div>${message.sender==='user'?'<button class="chat-message-menu-toggle" type="button" aria-label="Opções da mensagem" aria-expanded="false">⌄</button><div class="chat-message-menu" hidden><button class="chat-delete-message" type="button">Apagar mensagem</button></div>':''}</div><time>${new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date(message.created_at))}</time></article>`}).join(''):'<p class="dashboard-empty">Envie uma mensagem para começar a conversar com o Aura Tester.</p>';
  await Promise.all([...chatMessages.querySelectorAll('[data-private-path]')].map(async element=>{const url=await privateAttachmentUrl(element.dataset.privatePath);if(!url){element.textContent='Anexo indisponível';return}if(element.classList.contains('chat-private-image')){element.innerHTML=`<img src="${url}" alt="Foto privada enviada na conversa">`;element.addEventListener('click',()=>window.open(url,'_blank','noopener'))}else element.addEventListener('click',()=>window.open(url,'_blank','noopener'))}));chatMessages.scrollTop=chatMessages.scrollHeight}
async function loadChat(){showActiveConversation();document.querySelector('#chatUnread').hidden=true;document.querySelector('#chatNewBadge').hidden=true;let{data,error}=await window.auraSupabase.from('aura_tester_messages').select('id,sender,content,created_at,chat_attachments(storage_path,original_name,mime_type,size_bytes)').order('created_at');if(error&&/chat_attachments|relationship|schema cache/i.test(error.message))({data,error}=await window.auraSupabase.from('aura_tester_messages').select('id,sender,content,created_at').order('created_at'));if(error){chatMessages.innerHTML='<p class="dashboard-empty">Execute a migration 012 no Supabase para ativar o Aura Tester.</p>';return}await renderChat(data||[]);setTimeout(()=>document.querySelector('#chatInput').focus(),80)}
function showConversationList(){document.querySelector('.chat-shell').classList.add('show-contacts');document.querySelector('#chatClose').setAttribute('aria-expanded','true')}
function showActiveConversation(){document.querySelector('.chat-shell').classList.remove('show-contacts');document.querySelector('#chatClose').setAttribute('aria-expanded','false')}
function openChat(){showActiveConversation();document.querySelector('#openChatNav').click()}
function clearChatFile(){selectedChatFile=null;chatFile.value='';if(chatPreviewUrl)URL.revokeObjectURL(chatPreviewUrl);chatPreviewUrl='';chatPreview.hidden=true;chatPreview.innerHTML=''}
function chooseChatFile(file){const allowed=['image/jpeg','image/png','image/webp','application/pdf'];const limit=file.type.startsWith('image/')?10*1048576:20*1048576;if(!allowed.includes(file.type)){showToast('Envie apenas JPG, PNG, WebP ou PDF.','error','Formato não permitido');return}if(file.size>limit){showToast(`O limite é ${file.type.startsWith('image/')?'10':'20'} MB.`,'error','Arquivo muito grande');return}selectedChatFile=file;chatPreview.hidden=false;chatPreviewUrl=file.type.startsWith('image/')?URL.createObjectURL(file):'';chatPreview.innerHTML=`${chatPreviewUrl?`<img src="${chatPreviewUrl}" alt="Prévia do anexo">`:'<b>PDF</b>'}<span><strong>${chatEscape(file.name)}</strong><small>${chatSize(file.size)} · privado</small></span><button type="button" aria-label="Remover anexo">×</button>`;chatPreview.querySelector('button').addEventListener('click',clearChatFile)}
async function sanitizeChatFile(file){if(!file.type.startsWith('image/'))return file;const bitmap=await createImageBitmap(file);if(bitmap.width>6000||bitmap.height>6000){bitmap.close();throw new Error('A imagem possui dimensões muito grandes.')}const canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);bitmap.close();const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Não foi possível preparar a imagem.')),file.type,.9));return new File([blob],file.name,{type:file.type,lastModified:Date.now()})}
const chatContacts=document.querySelector('.chat-contacts');chatContacts.insertAdjacentHTML('afterbegin','<div class="chat-contacts-heading"><span>Suas mensagens</span><strong>Conversas</strong><small>Escolha uma conversa para continuar</small></div>');document.querySelector('#openChatButton').addEventListener('click',openChat);document.querySelector('#chatClose').addEventListener('click',showConversationList);document.querySelectorAll('.chat-contact').forEach(contact=>contact.addEventListener('click',()=>{showActiveConversation();loadChat()}));document.querySelector('#chatAttachButton').addEventListener('click',()=>chatFile.click());chatFile.addEventListener('change',event=>{if(event.target.files[0])chooseChatFile(event.target.files[0])});
chatMessages.addEventListener('click',async event=>{const toggle=event.target.closest('.chat-message-menu-toggle');if(toggle){const menu=toggle.nextElementSibling;chatMessages.querySelectorAll('.chat-message-menu').forEach(item=>{if(item!==menu)item.hidden=true});menu.hidden=!menu.hidden;toggle.setAttribute('aria-expanded',String(!menu.hidden));return}const button=event.target.closest('.chat-delete-message');if(!button)return;button.disabled=true;const messageId=Number(button.closest('[data-message-id]').dataset.messageId);const{data:path,error}=await window.auraSupabase.rpc('delete_own_chat_message',{p_message_id:messageId});if(error){button.disabled=false;showToast(error.message,'error','Não foi possível apagar');return}if(path)await window.auraSupabase.storage.from('chat-attachments').remove([path]);showToast('A mensagem foi removida da conversa.','success','Mensagem apagada');loadChat()});
document.addEventListener('click',event=>{if(!event.target.closest('.chat-bubble-shell'))chatMessages.querySelectorAll('.chat-message-menu').forEach(menu=>menu.hidden=true)});
document.querySelector('#chatForm').addEventListener('submit',async event=>{event.preventDefault();const input=document.querySelector('#chatInput'),content=input.value.trim();if(!content&&!selectedChatFile)return;const button=event.currentTarget.querySelector('[type="submit"]');button.disabled=true;let uploadedPath='';try{if(selectedChatFile){const safeFile=await sanitizeChatFile(selectedChatFile);const extension=safeFile.type==='application/pdf'?'pdf':safeFile.type.split('/')[1].replace('jpeg','jpg');uploadedPath=`${window.AURA_SESSION.user.id}/${crypto.randomUUID()}.${extension}`;const{error:uploadError}=await window.auraSupabase.storage.from('chat-attachments').upload(uploadedPath,safeFile,{contentType:safeFile.type,upsert:false});if(uploadError)throw uploadError;const{error}=await window.auraSupabase.rpc('send_aura_tester_attachment',{p_storage_path:uploadedPath,p_original_name:selectedChatFile.name,p_mime_type:safeFile.type,p_size_bytes:safeFile.size,p_caption:content||null});if(error)throw error}else{const{error}=await window.auraSupabase.rpc('send_aura_tester_message',{p_content:content});if(error)throw error}input.value='';clearChatFile();await loadChat()}catch(error){if(uploadedPath)await window.auraSupabase.storage.from('chat-attachments').remove([uploadedPath]);showToast(/send_aura_tester_attachment|chat-attachments|schema cache/i.test(error.message)?'Execute a migration 016 no Supabase para ativar anexos privados.':error.message,'error','Mensagem não enviada')}finally{button.disabled=false}});
