let auraCommunityTab='mine',activeAuraCommunity=null;
const communityEscape=(value='')=>{const node=document.createElement('span');node.textContent=value;return node.innerHTML};
const communityInitials=(name='Aura')=>name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
function ensureCommunityModal(){if(document.querySelector('#communityModalBackdrop'))return;const root=document.createElement('div');root.className='community-modal-backdrop';root.id='communityModalBackdrop';root.hidden=true;root.innerHTML='<section class="community-modal" role="dialog" aria-modal="true" aria-labelledby="communityModalTitle"><button class="modal-close" id="communityModalClose" type="button">×</button><div id="communityModalContent"></div></section>';document.body.appendChild(root);document.querySelector('#communityModalClose').onclick=closeCommunityModal;root.addEventListener('click',event=>{if(event.target===root)closeCommunityModal()})}
function openCommunityModal(content){ensureCommunityModal();document.querySelector('#communityModalContent').innerHTML=content;document.querySelector('#communityModalBackdrop').hidden=false;document.body.style.overflow='hidden'}
function closeCommunityModal(){document.querySelector('#communityModalBackdrop').hidden=true;document.body.style.overflow=''}
function communityError(error){showToast(/list_my_aura_communities|schema cache|does not exist/i.test(error?.message||'')?'Execute a migration 032 no Supabase para ativar Comunidades.':error.message,'error','Comunidades indisponíveis')}
async function loadCommunityInvites(){const{data,error}=await window.auraSupabase.rpc('list_my_aura_community_invites');if(error)return;const rows=data||[],panel=document.querySelector('#communityInvites'),badge=document.querySelector('#communityInviteCount');panel.hidden=!rows.length;badge.hidden=!rows.length;badge.textContent=rows.length;badge.dataset.count=rows.length;document.querySelector('#communityInviteList').innerHTML=rows.map(invite=>`<article class="community-invite-row"><span><strong>${communityEscape(invite.community_name)}</strong><small>${communityEscape(invite.inviter_name)} convidou você</small></span><div class="community-invite-actions"><button data-community-invite="${invite.id}" data-accept="true" type="button">Aceitar</button><button class="decline" data-community-invite="${invite.id}" data-accept="false" type="button">Recusar</button></div></article>`).join('')}
function renderCommunityCards(rows,discover=false){const list=document.querySelector('#communityList');list.innerHTML=rows.length?rows.map(row=>`<article class="community-card"><span class="community-card-mark">${communityEscape(communityInitials(row.name))}</span><h3>${communityEscape(row.name)}</h3><p>${communityEscape(row.description||'Uma comunidade Aura em evolução.')}</p><div class="community-card-meta"><span>${Number(row.member_count||0)} membros</span><span>${discover?'Pública':communityEscape(row.my_role==='owner'?'Criador':row.my_role==='admin'?'Administrador':'Membro')}</span></div><button type="button" data-community-open="${row.id}"${discover&&!row.joined?' data-community-join="true"':''}>${discover&&!row.joined?'Participar':'Abrir comunidade'}</button></article>`).join(''):'<p class="communities-empty">Nenhuma comunidade encontrada aqui ainda.</p>'}
async function loadAuraCommunities(){if(!window.AURA_SESSION)return;document.querySelector('#communityList').innerHTML='<p class="communities-empty">Carregando comunidades…</p>';await loadCommunityInvites();if(auraCommunityTab==='code'){renderJoinCode();return}const rpc=auraCommunityTab==='discover'?'discover_aura_communities':'list_my_aura_communities';const{data,error}=await window.auraSupabase.rpc(rpc);if(error){communityError(error);document.querySelector('#communityList').innerHTML='<p class="communities-empty">Execute a migration 032 para ativar este espaço.</p>';return}renderCommunityCards(data||[],auraCommunityTab==='discover')}
function openCreateCommunity(){openCommunityModal('<span class="section-kicker">NOVA COMUNIDADE</span><h2 id="communityModalTitle">Crie um círculo com propósito.</h2><p>Você será responsável pela administração e poderá convidar pessoas depois.</p><form class="community-form" id="createCommunityForm"><label>Nome<input id="communityName" maxlength="60" minlength="3" required placeholder="Ex.: Corrida Caxias"></label><label>Descrição<textarea id="communityDescription" maxlength="300" placeholder="Qual é o propósito desta comunidade?"></textarea></label><label>Quem pode entrar?<select id="communityVisibility"><option value="private">Somente por convite</option><option value="public">Qualquer pessoa pode participar</option></select></label><button class="primary-button" type="submit">Criar comunidade</button></form>');document.querySelector('#createCommunityForm').onsubmit=createCommunity}
async function createCommunity(event){event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;const{data,error}=await window.auraSupabase.rpc('create_aura_community',{p_name:document.querySelector('#communityName').value,p_description:document.querySelector('#communityDescription').value,p_visibility:document.querySelector('#communityVisibility').value});button.disabled=false;if(error)return communityError(error);closeCommunityModal();auraCommunityTab='mine';syncCommunityTabs();await loadAuraCommunities();showToast('Seu novo espaço já está pronto para receber pessoas.','success','Comunidade criada');openCommunity(data)}
async function openCommunity(id){const{data,error}=await window.auraSupabase.rpc('get_aura_community',{p_community_id:id});if(error)return communityError(error);activeAuraCommunity=data;const canManage=['owner','admin'].includes(data.my_role),members=data.members||[];openCommunityModal(`<span class="section-kicker">${data.visibility==='private'?'COMUNIDADE PRIVADA':'COMUNIDADE PÚBLICA'}</span><h2 id="communityModalTitle">${communityEscape(data.name)}</h2><p>${communityEscape(data.description||'Uma comunidade Aura em evolução.')}</p><div class="community-detail-actions">${canManage?'<button id="communityInviteButton" type="button">＋ Convidar pessoa</button><button id="communityShareButton" type="button">Compartilhar convite</button>':''}${data.my_role&&data.my_role!=='owner'?'<button id="communityLeaveButton" type="button">Sair da comunidade</button>':''}</div>${canManage&&data.invite_code?`<div class="community-code-box">Código de convite: <strong>${data.invite_code}</strong></div>`:''}<h3>Membros · ${members.length}</h3><div class="community-members">${members.map(member=>`<article class="community-member"><span class="community-member-avatar"${member.avatar_url?` style="background-image:url('${mediaUrl(member.avatar_url)}')"`:''}>${member.avatar_url?'':communityEscape(communityInitials(member.full_name))}</span><span><strong>${communityEscape(member.full_name)}</strong><small>@${communityEscape(member.username||'perfil-aura')} · ${communityEscape(member.role==='owner'?'Criador':member.role==='admin'?'Administrador':'Membro')}</small></span>${canManage&&member.role!=='owner'&&member.id!==window.AURA_SESSION.user.id?`<button data-community-remove="${member.id}" type="button">Remover</button>`:''}</article>`).join('')}</div>`);if(canManage){document.querySelector('#communityInviteButton').onclick=openInvitePerson;document.querySelector('#communityShareButton').onclick=shareCommunityInvite}document.querySelector('#communityLeaveButton')?.addEventListener('click',leaveCommunity);document.querySelectorAll('[data-community-remove]').forEach(button=>button.onclick=()=>removeCommunityMember(button.dataset.communityRemove))}
function openInvitePerson(){openCommunityModal(`<span class="section-kicker">CONVIDAR PESSOA</span><h2 id="communityModalTitle">Adicionar à ${communityEscape(activeAuraCommunity.name)}</h2><p>Digite o nome de usuário exato. A pessoa poderá aceitar ou recusar o convite.</p><form class="community-form" id="communityInviteForm"><label>Usuário<input id="communityInviteUsername" required placeholder="@usuario" autocomplete="off"></label><button class="primary-button" type="submit">Enviar convite</button></form>`);document.querySelector('#communityInviteForm').onsubmit=inviteCommunityPerson}
async function inviteCommunityPerson(event){event.preventDefault();const button=event.currentTarget.querySelector('button');button.disabled=true;const{error}=await window.auraSupabase.rpc('invite_to_aura_community',{p_community_id:activeAuraCommunity.id,p_username:document.querySelector('#communityInviteUsername').value});button.disabled=false;if(error)return communityError(error);closeCommunityModal();showToast('A pessoa verá o convite ao abrir Comunidades.','success','Convite enviado')}
async function shareCommunityInvite(){const code=activeAuraCommunity.invite_code,text=`Entre na comunidade ${activeAuraCommunity.name} na Aura 67 usando o código: ${code}`;try{if(navigator.share)await navigator.share({title:activeAuraCommunity.name,text});else{await navigator.clipboard.writeText(text);showToast('O código foi copiado.','success','Convite pronto')}}catch(error){if(error.name!=='AbortError')communityError(error)}}
function renderJoinCode(){document.querySelector('#communityList').innerHTML='<article class="community-card"><span class="community-card-mark">＋</span><h3>Entrar com código</h3><p>Cole o código enviado por um administrador da comunidade.</p><form class="community-form" id="communityCodeForm"><label>Código<input id="communityCode" required placeholder="00000000-0000-0000-0000-000000000000"></label><button type="submit">Entrar na comunidade</button></form></article>';document.querySelector('#communityCodeForm').onsubmit=joinByCode}
async function joinByCode(event){event.preventDefault();const{data,error}=await window.auraSupabase.rpc('join_aura_community_by_code',{p_code:document.querySelector('#communityCode').value.trim()});if(error)return communityError(error);auraCommunityTab='mine';syncCommunityTabs();await loadAuraCommunities();showToast('Você agora faz parte desta comunidade.','success','Convite aceito');openCommunity(data)}
async function joinPublicCommunity(id){const{error}=await window.auraSupabase.rpc('join_public_aura_community',{p_community_id:id});if(error)return communityError(error);showToast('Você entrou na comunidade.','success','Bem-vindo');openCommunity(id);loadAuraCommunities()}
async function respondCommunityInvite(id,accept){const{error}=await window.auraSupabase.rpc('respond_aura_community_invite',{p_invite_id:id,p_accept:accept});if(error)return communityError(error);showToast(accept?'Você entrou na comunidade.':'O convite foi recusado.','success',accept?'Convite aceito':'Convite recusado');loadAuraCommunities()}
async function leaveCommunity(){if(!confirm('Deseja sair desta comunidade?'))return;const{error}=await window.auraSupabase.rpc('leave_aura_community',{p_community_id:activeAuraCommunity.id});if(error)return communityError(error);closeCommunityModal();loadAuraCommunities()}
async function removeCommunityMember(profileId){if(!confirm('Remover esta pessoa da comunidade?'))return;const{error}=await window.auraSupabase.rpc('remove_aura_community_member',{p_community_id:activeAuraCommunity.id,p_profile_id:profileId});if(error)return communityError(error);openCommunity(activeAuraCommunity.id)}
function syncCommunityTabs(){document.querySelectorAll('[data-community-tab]').forEach(button=>button.classList.toggle('active',button.dataset.communityTab===auraCommunityTab))}
document.querySelector('#createCommunityButton').onclick=openCreateCommunity;document.querySelectorAll('[data-community-tab]').forEach(button=>button.onclick=()=>{auraCommunityTab=button.dataset.communityTab;syncCommunityTabs();loadAuraCommunities()});document.querySelector('#communityList').onclick=event=>{const button=event.target.closest('[data-community-open]');if(!button)return;if(button.dataset.communityJoin)joinPublicCommunity(button.dataset.communityOpen);else openCommunity(button.dataset.communityOpen)};document.querySelector('#communityInviteList').onclick=event=>{const button=event.target.closest('[data-community-invite]');if(button)respondCommunityInvite(button.dataset.communityInvite,button.dataset.accept==='true')};document.addEventListener('aura:session-ready',loadCommunityInvites);if(window.AURA_SESSION)loadCommunityInvites();
