const dashboardEsc=(value='')=>{const node=document.createElement('span');node.textContent=value;return node.innerHTML};
const dashboardDate=(date)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(date));
let visibleNotificationKeys=[];
const notificationStorageKey=()=>`aura67_dismissed_notifications_${window.AURA_SESSION.user.id}`;
function localDismissedNotifications(){try{return new Set(JSON.parse(localStorage.getItem(notificationStorageKey())||'[]'))}catch{return new Set()}}
async function dismissNotifications(keys){const local=localDismissedNotifications();keys.forEach(key=>local.add(key));localStorage.setItem(notificationStorageKey(),JSON.stringify([...local]));await window.auraSupabase.from('notification_dismissals').upsert(keys.map(notification_key=>({user_id:window.AURA_SESSION.user.id,notification_key})),{onConflict:'user_id,notification_key'});visibleNotificationKeys=visibleNotificationKeys.filter(key=>!keys.includes(key));document.querySelectorAll('.notification-entry').forEach(entry=>{if(keys.includes(entry.dataset.key))entry.remove()});if(!document.querySelector('.notification-entry'))document.querySelector('#notificationList').innerHTML='<p class="dashboard-empty">Nenhuma notificação no momento.</p>';document.querySelector('#notificationDot').hidden=true;document.querySelector('#mobileNotificationButton i').hidden=true}

async function loadDashboardActivity(){
  if(!window.AURA_SESSION)return;
  const start=new Date();start.setDate(start.getDate()-6);start.setHours(0,0,0,0);
  const{data,error}=await window.auraSupabase.from('action_completions').select('id,completed_on,base_xp,bonus_xp,created_at,actions_catalog(title,icon)').gte('completed_on',start.toISOString().slice(0,10)).order('created_at',{ascending:false});
  if(error){showToast('Não foi possível carregar a atividade recente.','error');return}
  const rows=data||[];const days=Array.from({length:7},(_,index)=>{const day=new Date(start);day.setDate(start.getDate()+index);return day.toISOString().slice(0,10)});const counts=days.map(day=>rows.filter(row=>row.completed_on===day).length);const max=Math.max(1,...counts);const points=counts.map((count,index)=>`${index*700/6},${170-(count/max)*145}`);
  document.querySelector('#activityScale').innerHTML=[1,.75,.5,.25,0].map(value=>`<span>${Math.round(max*value)}</span>`).join('');document.querySelector('#activityDays').innerHTML=days.map(day=>`<span>${new Intl.DateTimeFormat('pt-BR',{weekday:'short',timeZone:'UTC'}).format(new Date(`${day}T12:00:00Z`)).replace('.','')}</span>`).join('');
  document.querySelector('#weekActions').textContent=rows.length;document.querySelector('#weekXp').textContent=rows.reduce((sum,row)=>sum+row.base_xp+row.bonus_xp,0);const active=counts.filter(Boolean).length;document.querySelector('#activeDays').textContent=active;document.querySelector('#weekConsistency').textContent=`${Math.round(active/7*100)}%`;
  const line=`M${points.join(' L')}`;document.querySelector('#activityLine').setAttribute('d',line);document.querySelector('#activityArea').setAttribute('d',`${line} L700,180 L0,180 Z`);const[x,y]=points.at(-1).split(',');document.querySelector('#activityDot').setAttribute('cx',x);document.querySelector('#activityDot').setAttribute('cy',y);
  const local=localDismissedNotifications();const{data:dismissed}=await window.auraSupabase.from('notification_dismissals').select('notification_key');(dismissed||[]).forEach(item=>local.add(item.notification_key));const notificationRows=rows.slice(0,8).map(row=>({...row,key:`completion:${row.id}`})).filter(row=>!local.has(row.key));visibleNotificationKeys=notificationRows.map(row=>row.key);const notices=notificationRows.map(row=>`<article class="notification-entry" data-key="${row.key}"><span>${dashboardEsc(row.actions_catalog?.icon||'✓')}</span><div><strong>${dashboardEsc(row.actions_catalog?.title||'Ação concluída')}</strong><small>Você conquistou ${row.base_xp+row.bonus_xp} XP.</small><time>${dashboardDate(row.created_at)}</time></div><button class="notification-delete" type="button" aria-label="Apagar notificação">×</button></article>`).join('');document.querySelector('#notificationList').innerHTML=notices||'<p class="dashboard-empty">Nenhuma atualização recente. Suas conquistas aparecerão aqui.</p>';document.querySelector('#notificationDot').hidden=!notificationRows.length;document.querySelector('#mobileNotificationButton i').hidden=!notificationRows.length;
}

let dashboardProjects=[];
let editingProjectId=null;
function celebrateProject(){const layer=document.createElement('div');layer.className='project-celebration';layer.innerHTML=Array.from({length:42},(_,index)=>`<i style="--x:${Math.random()*100}%;--delay:${Math.random()*.7}s;--color:${['#ff315f','#ffb800','#7657ec','#19b77e','#168eea'][index%5]}"></i>`).join('')+'<strong>Projeto concluído!<small>Sua constância virou conquista ✦</small></strong>';document.body.appendChild(layer);setTimeout(()=>layer.remove(),4200)}
const projectFields={title:document.querySelector('#itemName'),goal:document.querySelector('#projectGoal'),next:document.querySelector('#projectNextStep'),progress:document.querySelector('#projectProgress'),status:document.querySelector('#projectStatus')};
function startProjectCreate(){editingProjectId=null;Object.values(projectFields).forEach(field=>{if(field.tagName==='SELECT')field.value='active';else field.value=field.type==='range'?0:''});document.querySelector('#projectEditFields').hidden=true;document.querySelector('#projectDeleteButton').hidden=true;document.querySelector('#modalTitle').textContent='Criar um projeto';document.querySelector('#modalSubmit').textContent='Criar projeto';document.querySelector('#projectProgressValue').textContent='0%';openModal()}
function openProjectEditor(id,continueMode=false){const project=dashboardProjects.find(item=>item.id===id);if(!project)return;editingProjectId=id;projectFields.title.value=project.title;projectFields.goal.value=project.goal;projectFields.next.value=project.next_step;projectFields.progress.value=project.progress;projectFields.status.value=project.status;document.querySelector('#projectProgressValue').textContent=`${project.progress}%`;document.querySelector('#projectEditFields').hidden=false;document.querySelector('#projectDeleteButton').hidden=false;document.querySelector('#modalTitle').textContent=continueMode?'Continuar projeto':'Editar projeto';document.querySelector('#modalSubmit').textContent='Salvar alterações';openModal();if(continueMode)setTimeout(()=>projectFields.next.select(),80)}
async function loadProjects(){const{data,error}=await window.auraSupabase.from('user_projects').select('*').order('updated_at',{ascending:false}).limit(100);const list=document.querySelector('#projectList'),createButton=document.querySelector('#openProjectButton');if(error){list.innerHTML='<p class="dashboard-empty">Ative a migration 010 para criar projetos.</p>';return}dashboardProjects=data||[];const hasProjects=dashboardProjects.length>0;createButton.innerHTML=hasProjects?'Criar novo projeto <span>＋</span>':'Criar meu primeiro projeto <span>→</span>';list.innerHTML=hasProjects?dashboardProjects.map(project=>`<article class="project-row" data-project-id="${project.id}"><span class="project-thumb">${dashboardEsc(project.title[0].toUpperCase())}</span><span class="project-info"><strong>${dashboardEsc(project.title)}</strong><small>Próximo passo: ${dashboardEsc(project.next_step)}</small><i><b style="width:${project.progress}%"></b></i></span><span class="project-progress">${project.progress}%</span><div class="project-actions"><button type="button" data-project-action="continue">Continuar</button><button type="button" data-project-action="edit">Editar</button></div></article>`).join(''):'<p class="dashboard-empty">Nenhum projeto criado ainda.</p>'}

document.querySelector('#projectProgress').addEventListener('input',event=>document.querySelector('#projectProgressValue').textContent=`${event.target.value}%`);
document.querySelector('#projectList').addEventListener('click',event=>{const action=event.target.closest('[data-project-action]');if(!action)return;const id=action.closest('[data-project-id]').dataset.projectId;openProjectEditor(id,action.dataset.projectAction==='continue')});
document.querySelector('#modalSubmit').addEventListener('click',async()=>{const title=projectFields.title.value.trim(),goal=projectFields.goal.value.trim(),next=projectFields.next.value.trim();if(!title||!goal||!next){showToast('Preencha o nome, o objetivo e o próximo passo.','error','Complete o projeto');return}const button=document.querySelector('#modalSubmit');button.disabled=true;const wasEditing=Boolean(editingProjectId);const rpc=wasEditing?window.auraSupabase.rpc('update_private_project',{p_project_id:editingProjectId,p_title:title,p_goal:goal,p_next_step:next,p_progress:Number(projectFields.progress.value),p_status:projectFields.status.value}):window.auraSupabase.rpc('create_private_project',{p_title:title,p_goal:goal,p_next_step:next});const{data,error}=await rpc;button.disabled=false;if(error){showToast(/create_private_project|update_private_project|schema cache/i.test(error.message)?'Execute a migration 014 no Supabase para ativar projetos privados.':error.message,'error',wasEditing?'Não foi possível atualizar':'Não foi possível criar');return}editingProjectId=null;closeModal();if(data?.completed)celebrateProject();const earned=Number(data?.earned_points||0);showToast(earned?`Projeto salvo e +${earned} pontos conquistados.`:(wasEditing?'As mudanças do projeto foram salvas.':'Projeto criado.'),'success',data?.completed?'Conquista confirmada':wasEditing?'Projeto atualizado':'Projeto pronto');await loadProjects();if(typeof loadProfile==='function'&&window.AURA_SESSION)loadProfile(window.AURA_SESSION);if(typeof loadRealRanking==='function')loadRealRanking()});
document.querySelector('#projectDeleteButton').addEventListener('click',async()=>{const project=dashboardProjects.find(item=>item.id===editingProjectId);if(!project||!await confirmProjectDeletion(project.title))return;const button=document.querySelector('#projectDeleteButton');button.disabled=true;const{data,error}=await window.auraSupabase.rpc('delete_private_project',{p_project_id:project.id});button.disabled=false;if(error){showToast(/delete_private_project|schema cache/i.test(error.message)?'Execute a migration 019 no Supabase para ativar a exclusão.':error.message,'error','Não foi possível excluir');return}editingProjectId=null;closeModal();showToast(data.removed_points?`Projeto removido e ${data.removed_points} pontos associados retirados.`:'O projeto foi removido.','success','Projeto excluído');await loadProjects();if(typeof loadProfile==='function')loadProfile(window.AURA_SESSION);if(typeof loadRealRanking==='function')loadRealRanking()});
['openProjectButton','quickProjectButton'].forEach(id=>document.querySelector(`#${id}`).addEventListener('click',startProjectCreate));
function toggleNotifications(open){const panel=document.querySelector('#notificationBackdrop');panel.hidden=!open;document.body.style.overflow=open?'hidden':'';if(open&&history.state?.auraOverlay!=='notifications')history.pushState({...(history.state||{}),auraOverlay:'notifications'},'',location.href);if(!open&&history.state?.auraOverlay==='notifications')history.back()}
document.querySelector('#notificationButton').addEventListener('click',()=>{toggleNotifications(true);document.querySelector('#notificationDot').hidden=true});document.querySelector('#mobileNotificationButton').addEventListener('click',()=>{toggleNotifications(true);document.querySelector('#mobileNotificationButton i').hidden=true});document.querySelector('#notificationClose').addEventListener('click',()=>toggleNotifications(false));document.querySelector('#notificationBackdrop').addEventListener('click',event=>{if(event.target.id==='notificationBackdrop')toggleNotifications(false)});window.addEventListener('popstate',()=>{if(!document.querySelector('#notificationBackdrop').hidden){document.querySelector('#notificationBackdrop').hidden=true;document.body.style.overflow=''}});
document.querySelector('#notificationList').addEventListener('click',event=>{const button=event.target.closest('.notification-delete');if(button)dismissNotifications([button.closest('.notification-entry').dataset.key])});document.querySelector('#clearNotifications').addEventListener('click',()=>{if(visibleNotificationKeys.length)dismissNotifications([...visibleNotificationKeys])});
document.addEventListener('aura:session-ready',()=>Promise.all([loadDashboardActivity(),loadProjects()]));if(window.AURA_SESSION)Promise.all([loadDashboardActivity(),loadProjects()]);
