const dashboardEsc=(value='')=>{const node=document.createElement('span');node.textContent=value;return node.innerHTML};
const dashboardDate=(date)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(date));

async function loadDashboardActivity(){
  if(!window.AURA_SESSION)return;
  const start=new Date();start.setDate(start.getDate()-6);start.setHours(0,0,0,0);
  const{data,error}=await window.auraSupabase.from('action_completions').select('completed_on,base_xp,bonus_xp,created_at,actions_catalog(title,icon)').gte('completed_on',start.toISOString().slice(0,10)).order('created_at',{ascending:false});
  if(error){showToast('Não foi possível carregar a atividade recente.','error');return}
  const rows=data||[];const days=Array.from({length:7},(_,index)=>{const day=new Date(start);day.setDate(start.getDate()+index);return day.toISOString().slice(0,10)});const counts=days.map(day=>rows.filter(row=>row.completed_on===day).length);const max=Math.max(1,...counts);const points=counts.map((count,index)=>`${index*700/6},${170-(count/max)*145}`);
  document.querySelector('#activityScale').innerHTML=[1,.75,.5,.25,0].map(value=>`<span>${Math.round(max*value)}</span>`).join('');document.querySelector('#activityDays').innerHTML=days.map(day=>`<span>${new Intl.DateTimeFormat('pt-BR',{weekday:'short',timeZone:'UTC'}).format(new Date(`${day}T12:00:00Z`)).replace('.','')}</span>`).join('');
  document.querySelector('#weekActions').textContent=rows.length;document.querySelector('#weekXp').textContent=rows.reduce((sum,row)=>sum+row.base_xp+row.bonus_xp,0);const active=counts.filter(Boolean).length;document.querySelector('#activeDays').textContent=active;document.querySelector('#weekConsistency').textContent=`${Math.round(active/7*100)}%`;
  const line=`M${points.join(' L')}`;document.querySelector('#activityLine').setAttribute('d',line);document.querySelector('#activityArea').setAttribute('d',`${line} L700,180 L0,180 Z`);const[x,y]=points.at(-1).split(',');document.querySelector('#activityDot').setAttribute('cx',x);document.querySelector('#activityDot').setAttribute('cy',y);
  const notices=rows.slice(0,8).map(row=>`<article class="notification-entry"><span>${dashboardEsc(row.actions_catalog?.icon||'✓')}</span><div><strong>${dashboardEsc(row.actions_catalog?.title||'Ação concluída')}</strong><small>Você conquistou ${row.base_xp+row.bonus_xp} XP.</small><time>${dashboardDate(row.created_at)}</time></div></article>`).join('');document.querySelector('#notificationList').innerHTML=notices||'<p class="dashboard-empty">Nenhuma atualização recente. Suas conquistas aparecerão aqui.</p>';document.querySelector('#notificationDot').hidden=!rows.length;document.querySelector('#mobileNotificationButton i').hidden=!rows.length;
}

async function loadProjects(){const{data,error}=await window.auraSupabase.from('user_projects').select('*').order('updated_at',{ascending:false}).limit(5);const list=document.querySelector('#projectList');if(error){list.innerHTML='<p class="dashboard-empty">Ative a migration 010 para criar projetos.</p>';return}list.innerHTML=data?.length?data.map(project=>`<button class="project-row" type="button"><span class="project-thumb">${dashboardEsc(project.title[0].toUpperCase())}</span><span class="project-info"><strong>${dashboardEsc(project.title)}</strong><small>Próximo passo: ${dashboardEsc(project.next_step)}</small></span><span class="project-progress">${project.progress}%</span></button>`).join(''):'<p class="dashboard-empty">Nenhum projeto criado ainda.</p>'}

document.querySelector('#modalSubmit').addEventListener('click',async()=>{const title=document.querySelector('#itemName').value.trim(),goal=document.querySelector('#projectGoal').value.trim(),next=document.querySelector('#projectNextStep').value.trim();if(!title||!goal||!next){showToast('Preencha o nome, o objetivo e o próximo passo.','error','Complete o projeto');return}const button=document.querySelector('#modalSubmit');button.disabled=true;const{error}=await window.auraSupabase.from('user_projects').insert({user_id:window.AURA_SESSION.user.id,title,goal,next_step:next});button.disabled=false;if(error){showToast(error.message.includes('user_projects')?'Execute a migration 010 no Supabase.':error.message,'error','Não foi possível criar');return}['itemName','projectGoal','projectNextStep'].forEach(id=>document.querySelector(`#${id}`).value='');closeModal();showToast('Seu projeto foi criado com um próximo passo claro.','success','Projeto pronto');loadProjects()});
['openProjectButton','quickProjectButton'].forEach(id=>document.querySelector(`#${id}`).addEventListener('click',openModal));
function toggleNotifications(open){const panel=document.querySelector('#notificationBackdrop');panel.hidden=!open;document.body.style.overflow=open?'hidden':'';if(open&&history.state?.auraOverlay!=='notifications')history.pushState({...(history.state||{}),auraOverlay:'notifications'},'',location.href);if(!open&&history.state?.auraOverlay==='notifications')history.back()}
document.querySelector('#notificationButton').addEventListener('click',()=>{toggleNotifications(true);document.querySelector('#notificationDot').hidden=true});document.querySelector('#mobileNotificationButton').addEventListener('click',()=>{toggleNotifications(true);document.querySelector('#mobileNotificationButton i').hidden=true});document.querySelector('#notificationClose').addEventListener('click',()=>toggleNotifications(false));document.querySelector('#notificationBackdrop').addEventListener('click',event=>{if(event.target.id==='notificationBackdrop')toggleNotifications(false)});window.addEventListener('popstate',()=>{if(!document.querySelector('#notificationBackdrop').hidden){document.querySelector('#notificationBackdrop').hidden=true;document.body.style.overflow=''}});
document.addEventListener('aura:session-ready',()=>Promise.all([loadDashboardActivity(),loadProjects()]));if(window.AURA_SESSION)Promise.all([loadDashboardActivity(),loadProjects()]);
