const paletteHues=[{name:'Violeta',h:258},{name:'Rosa',h:335},{name:'Vermelho',h:352},{name:'Laranja',h:27},{name:'Dourado',h:46},{name:'Verde',h:153},{name:'Turquesa',h:181},{name:'Azul',h:218},{name:'Índigo',h:238},{name:'Grafite',h:225,s:10}];
let selectedPaletteHue=258;
function hslToHex(h,s,l){s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return`#${[r,g,b].map(v=>Math.round((v+m)*255).toString(16).padStart(2,'0')).join('')}`}
function hexHue(hex){const r=parseInt(hex.slice(1,3),16)/255,g=parseInt(hex.slice(3,5),16)/255,b=parseInt(hex.slice(5,7),16)/255,max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;if(!d)return 225;let h=max===r?60*((g-b)/d%6):max===g?60*((b-r)/d+2):60*((r-g)/d+4);return(h+360)%360}
function closestPaletteHue(hex){const target=hexHue(hex);return paletteHues.reduce((best,item)=>Math.min(Math.abs(item.h-target),360-Math.abs(item.h-target))<Math.min(Math.abs(best.h-target),360-Math.abs(best.h-target))?item:best,paletteHues[0])}
function renderTonePalette(){const family=paletteHues.find(item=>item.h===selectedPaletteHue)||paletteHues[0],saturations=family.s?[12,18,24,30]:[48,62,74,86],lights=[72,61,50,40,31];document.querySelector('#tonePalette').innerHTML=saturations.flatMap((s,row)=>lights.map((l,column)=>{const color=hslToHex(family.h,s,l);return`<button type="button" data-tone="${color}" style="--tone:${color}" aria-label="${family.name}, tom ${row*5+column+1}"></button>`})).join('');document.querySelectorAll('[data-tone]').forEach(button=>button.addEventListener('click',()=>selectPaletteColor(button.dataset.tone)));highlightSelectedTone()}
function highlightSelectedTone(){const value=document.querySelector('#designColor').value.toLowerCase();document.querySelectorAll('[data-tone]').forEach(button=>button.classList.toggle('selected',button.dataset.tone===value));document.querySelector('#paletteCurrentHex').textContent=value.toUpperCase();document.querySelector('#designHex').value=value.toUpperCase();const preview=document.querySelector('#themeLivePreview');preview.style.setProperty('--preview-color',value);preview.style.setProperty('--preview-dark',shiftColor(value,-70))}
function selectPaletteColor(color){document.querySelector('#designColor').value=color;applyGlobalTheme(color);highlightSelectedTone();scheduleThemeSave();updatePreview()}
function syncPaletteFromColor(){const input=document.querySelector('#designColor');if(!input)return;const family=closestPaletteHue(input.value);selectedPaletteHue=family.h;document.querySelectorAll('[data-palette-hue]').forEach(button=>button.classList.toggle('selected',Number(button.dataset.paletteHue)===selectedPaletteHue));renderTonePalette();const locked=input.disabled;document.querySelectorAll('[data-palette-hue],[data-tone],#designHex').forEach(control=>control.disabled=locked)}
function buildModernPalette(){const picker=document.querySelector('.theme-picker');picker.innerHTML=`<legend>Crie sua paleta</legend><div class="theme-live-preview" id="themeLivePreview"><div><span>PRÉVIA DO SEU ESPAÇO</span><strong>Sua Aura, sua identidade.</strong><small>Botões, destaques e detalhes acompanham o tom escolhido.</small><button type="button">Continuar evoluindo</button></div><i></i><i></i></div><div class="palette-section-head"><span><b>1</b><strong>Escolha uma cor</strong></span><small>Famílias de cores</small></div><div class="palette-hues" id="themeSwatches">${paletteHues.map(item=>`<button type="button" data-palette-hue="${item.h}" style="--hue:${hslToHex(item.h,item.s||78,52)}" aria-label="${item.name}"><i></i><small>${item.name}</small></button>`).join('')}</div><div class="palette-section-head"><span><b>2</b><strong>Escolha o tom</strong></span><small>Do suave ao intenso</small></div><div class="tone-palette" id="tonePalette"></div><div class="palette-advanced"><span class="palette-current"><i></i><span><small>COR ATUAL</small><strong id="paletteCurrentHex">#7657EC</strong></span></span><label>Hexadecimal<input id="designHex" maxlength="7" value="#7657EC" spellcheck="false"></label><label class="native-color">Personalizada<input id="designColor" type="color" value="#7657ec"></label></div>`;document.querySelectorAll('[data-palette-hue]').forEach(button=>button.addEventListener('click',()=>{selectedPaletteHue=Number(button.dataset.paletteHue);document.querySelectorAll('[data-palette-hue]').forEach(item=>item.classList.toggle('selected',item===button));renderTonePalette()}));document.querySelector('#designColor').addEventListener('input',event=>selectPaletteColor(event.target.value));document.querySelector('#designHex').addEventListener('change',event=>{let value=event.target.value.trim();if(!value.startsWith('#'))value=`#${value}`;if(!/^#[0-9a-f]{6}$/i.test(value)){event.target.value=document.querySelector('#designColor').value.toUpperCase();return}selectPaletteColor(value.toLowerCase());syncPaletteFromColor()});syncPaletteFromColor()}
buildModernPalette();document.addEventListener('aura:profile-ready',syncPaletteFromColor);document.querySelector('#openDesignButton').addEventListener('click',()=>setTimeout(syncPaletteFromColor,0));
