let fireworksBusy=false;
function formatFireworkNumber(value){return Number(value||0).toLocaleString('pt-BR')}
function renderFireworkStats(data,prefix='public'){document.querySelector(`#${prefix}FireCount`).textContent=formatFireworkNumber(data?.fire_count);document.querySelector(`#${prefix}FirePeople`).textContent=formatFireworkNumber(data?.people_count)}
function launchProfileFireworks(){const layer=document.createElement('div');layer.className='firework-layer';document.body.appendChild(layer);const lite=document.documentElement.classList.contains('aura-motion-lite')||matchMedia('(prefers-reduced-motion: reduce)').matches;const colors=['#ffcc45','#ff4f70','#55d6ff','#9cff57','#d98cff'];const rockets=lite?1:3;for(let i=0;i<rockets;i++){const launch=25+i*(50/Math.max(1,rockets-1)),drift=(50-launch)+(i-1)*8,color=colors[(Date.now()+i)%colors.length];const rocket=document.createElement('i');rocket.className='firework-rocket';rocket.style.cssText=`--launch-x:${launch}%;--drift:${drift}vw;--fire-color:${color}`;layer.appendChild(rocket);setTimeout(()=>{const burst=document.createElement('span');burst.className='firework-burst';burst.style.cssText=`--burst-x:${48+(i-1)*12}%;--burst-y:${42+(i%2)*7}%;--fire-color:${color}`;const count=lite?10:18;for(let n=0;n<count;n++){const spark=document.createElement('i');spark.className='firework-spark';spark.style.cssText=`--angle:${n*360/count}deg;--distance:${lite?42:65+Math.random()*28}px`;burst.appendChild(spark)}layer.appendChild(burst)},720+i*70)}setTimeout(()=>layer.remove(),2100)}
async function loadFireworkStats(profileId,prefix){const{data,error}=await window.auraSupabase.rpc('get_profile_firework_stats',{p_profile_id:profileId});if(!error&&data)renderFireworkStats(data,prefix);return{data,error}}
async function sendFirework(profileId,prefix,button){launchProfileFireworks();if(profileId===window.AURA_SESSION?.user.id)return;if(fireworksBusy)return;fireworksBusy=true;button.disabled=true;const{data,error}=await window.auraSupabase.rpc('send_profile_firework',{p_profile_id:profileId});button.disabled=false;fireworksBusy=false;if(error){showToast(/send_profile_firework|get_profile_firework_stats|schema cache/i.test(error.message)?'Execute a migration 022 no Supabase para ativar os Fogos.':error.message,'error','Fogo não registrado');return}renderFireworkStats(data,prefix);showToast('Seu Fogo agora faz parte deste perfil.','success','Fogo enviado 🎆')}
document.querySelector('#ownFireworksButton').addEventListener('click',launchProfileFireworks);
document.querySelector('#fireworksButton').addEventListener('click',event=>sendFirework(window.AURA_VIEWED_PROFILE_ID,'public',event.currentTarget));
document.addEventListener('aura:session-ready',()=>loadFireworkStats(window.AURA_SESSION.user.id,'own'));
document.addEventListener('aura:public-profile-opened',event=>loadFireworkStats(event.detail.profileId,'public'));
if(window.AURA_SESSION)loadFireworkStats(window.AURA_SESSION.user.id,'own');
