let fireworksBusy=false,activeFireworkShows=0;
function formatFireworkNumber(value){return Number(value||0).toLocaleString('pt-BR')}
function renderFireworkStats(data,prefix='public'){document.querySelector(`#${prefix}FireCount`).textContent=formatFireworkNumber(data?.fire_count);document.querySelector(`#${prefix}FirePeople`).textContent=formatFireworkNumber(data?.people_count)}
function launchProfileFireworks(){if(activeFireworkShows>=3)return false;activeFireworkShows++;const layer=document.createElement('div');layer.className='firework-layer';document.body.appendChild(layer);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,lite=reduced||document.documentElement.classList.contains('aura-motion-lite')||((navigator.hardwareConcurrency||8)<=4&&(navigator.deviceMemory||4)<=3);const colors=['#ffd84a','#ff476f','#45d9ff','#85ff65','#d779ff','#ff8d38','#ffffff'];const rockets=reduced?1:lite?3:7;for(let i=0;i<rockets;i++){const launch=8+Math.random()*84,burstX=10+Math.random()*80,burstY=15+Math.random()*43,drift=burstX-launch,color=colors[(Date.now()+i*3)%colors.length],delay=i*(lite?170:125);const rocket=document.createElement('i');rocket.className='firework-rocket';rocket.style.cssText=`--launch-x:${launch}%;--drift:${drift}vw;--rise:${100-burstY}vh;--fire-color:${color};--rocket-delay:${delay}ms`;layer.appendChild(rocket);setTimeout(()=>{const burst=document.createElement('span');burst.className='firework-burst';burst.style.cssText=`--burst-x:${burstX}%;--burst-y:${burstY}%;--fire-color:${color}`;const count=reduced?10:lite?18:32;for(let n=0;n<count;n++){const spark=document.createElement('i');spark.className='firework-spark';spark.style.cssText=`--angle:${n*360/count+(Math.random()*5-2.5)}deg;--distance:${reduced?48:lite?72+Math.random()*30:105+Math.random()*70}px;--spark-delay:${Math.random()*90}ms`;burst.appendChild(spark)}if(!reduced){const ring=document.createElement('i');ring.className='firework-ring';burst.appendChild(ring)}layer.appendChild(burst)},720+delay)}setTimeout(()=>{layer.remove();activeFireworkShows=Math.max(0,activeFireworkShows-1)},lite?2800:3600);return true}
async function loadFireworkStats(profileId,prefix){const{data,error}=await window.auraSupabase.rpc('get_profile_firework_stats',{p_profile_id:profileId});if(!error&&data)renderFireworkStats(data,prefix);return{data,error}}
async function sendFirework(profileId,prefix,button){const ownProfile=profileId===window.AURA_SESSION?.user.id;if(!ownProfile&&fireworksBusy)return;if(!launchProfileFireworks())return;if(ownProfile)return;fireworksBusy=true;button.disabled=true;const{data,error}=await window.auraSupabase.rpc('send_profile_firework',{p_profile_id:profileId});button.disabled=false;fireworksBusy=false;if(error){showToast(/send_profile_firework|get_profile_firework_stats|schema cache/i.test(error.message)?'Execute a migration 022 no Supabase para ativar os Fogos.':error.message,'error','Fogo não registrado');return}renderFireworkStats(data,prefix);showToast('Seu Fogo agora faz parte deste perfil.','success','Fogo enviado 🎆')}
document.querySelector('#ownFireworksButton').addEventListener('click',event=>sendFirework(window.AURA_SESSION?.user.id,'own',event.currentTarget));
document.querySelector('#fireworksButton').addEventListener('click',event=>sendFirework(window.AURA_VIEWED_PROFILE_ID,'public',event.currentTarget));
document.addEventListener('aura:session-ready',()=>loadFireworkStats(window.AURA_SESSION.user.id,'own'));
document.addEventListener('aura:public-profile-opened',event=>loadFireworkStats(event.detail.profileId,'public'));
if(window.AURA_SESSION)loadFireworkStats(window.AURA_SESSION.user.id,'own');
