let fireworksBusy=false,activeFireworkShows=0;
function formatFireworkNumber(value){return Number(value||0).toLocaleString('pt-BR')}
function renderFireworkStats(data,prefix='public'){document.querySelector(`#${prefix}FireCount`).textContent=formatFireworkNumber(data?.fire_count);document.querySelector(`#${prefix}FirePeople`).textContent=formatFireworkNumber(data?.people_count)}
function launchProfileFireworks(){if(activeFireworkShows>=1)return false;activeFireworkShows++;const layer=document.createElement('div');layer.className='firework-layer';document.body.appendChild(layer);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,lite=document.documentElement.classList.contains('aura-motion-lite');const colors=['#ffcc45','#ff4f70','#55d6ff','#9cff57','#d98cff','#ff8747'],rockets=reduced?1:6,targets=[32,40,48,56,64,72].sort(()=>Math.random()-.5);for(let i=0;i<rockets;i++){const launch=rockets===1?50:10+i*16+(Math.random()*6-3),burstX=rockets===1?50:targets[i]+(Math.random()*5-2.5),burstY=18+Math.random()*40,drift=burstX-launch,color=colors[(Date.now()+i)%colors.length];const rocket=document.createElement('i');rocket.className='firework-rocket';rocket.style.cssText=`--launch-x:${launch}%;--drift:${drift}vw;--fire-color:${color}`;layer.appendChild(rocket);setTimeout(()=>{const burst=document.createElement('span');burst.className='firework-burst';burst.style.cssText=`--burst-x:${burstX}%;--burst-y:${burstY}%;--fire-color:${color}`;const count=reduced?10:lite?10:18;for(let n=0;n<count;n++){const spark=document.createElement('i');spark.className='firework-spark';spark.style.cssText=`--angle:${n*360/count}deg;--distance:${lite?42:65+Math.random()*28}px`;burst.appendChild(spark)}const ring=document.createElement('i');ring.className='firework-ring';burst.appendChild(ring);layer.appendChild(burst)},720+i*70)}setTimeout(()=>{layer.remove();activeFireworkShows=0},2500);return true}
async function loadFireworkStats(profileId,prefix){const{data,error}=await window.auraSupabase.rpc('get_profile_firework_stats',{p_profile_id:profileId});if(!error&&data)renderFireworkStats(data,prefix);return{data,error}}
async function claimOfflineFireworks(){const{data,error}=await window.auraSupabase.rpc('claim_my_offline_fireworks');if(error){if(!/claim_my_offline_fireworks|schema cache/i.test(error.message))console.warn('Não foi possível receber os Fogos pendentes.',error);return}const count=Number(data?.fire_count||0);if(!count)return;setTimeout(()=>{launchProfileFireworks();showToast(`Você recebeu ${count} ${count===1?'Fogo':'Fogos'} enquanto esteve fora: +${Number(data.aura_earned||0).toLocaleString('pt-BR')} Aura e +${Number(data.honor_earned||0).toLocaleString('pt-BR')} Honra.`,'success','A comunidade celebrou você!')},500);setTimeout(()=>{loadFireworkStats(window.AURA_SESSION.user.id,'own');if(typeof loadProfile==='function')loadProfile(window.AURA_SESSION);if(typeof loadRealRanking==='function')loadRealRanking()},1100)}
async function sendFirework(profileId,prefix,button){const ownProfile=profileId===window.AURA_SESSION?.user.id;if(!ownProfile&&fireworksBusy)return;if(!launchProfileFireworks())return;if(ownProfile)return;fireworksBusy=true;button.disabled=true;const{data,error}=await window.auraSupabase.rpc('send_profile_firework',{p_profile_id:profileId});button.disabled=false;fireworksBusy=false;if(error){showToast(/send_profile_firework|get_profile_firework_stats|schema cache/i.test(error.message)?'Execute a migration 022 no Supabase para ativar os Fogos.':error.message,'error','Fogo não registrado');return}renderFireworkStats(data,prefix);showToast('Seu Fogo agora faz parte deste perfil.','success','Fogo enviado 🎆')}
document.querySelector('#ownFireworksButton').addEventListener('click',event=>sendFirework(window.AURA_SESSION?.user.id,'own',event.currentTarget));
document.querySelector('#fireworksButton').addEventListener('click',event=>sendFirework(window.AURA_VIEWED_PROFILE_ID,'public',event.currentTarget));
document.addEventListener('aura:session-ready',()=>{loadFireworkStats(window.AURA_SESSION.user.id,'own');claimOfflineFireworks()});
document.addEventListener('aura:public-profile-opened',event=>loadFireworkStats(event.detail.profileId,'public'));
if(window.AURA_SESSION){loadFireworkStats(window.AURA_SESSION.user.id,'own');claimOfflineFireworks()}
