let identityAudio=null;
let identityData=null;
const energyLabels={serena:'🌿 Serena',focada:'🎯 Focada',criativa:'✨ Criativa',corajosa:'🔥 Corajosa',equilibrada:'☯ Equilibrada',celebrando:'🎉 Celebrando'};
const musicLabels={silencio:'Sem trilha',aurora:'Aurora calma',fluxo:'Fluxo profundo',horizonte:'Horizonte leve',centelha:'Centelha vibrante'};

function identityList(value,max){return String(value||'').split(',').map(item=>item.trim()).filter(Boolean).slice(0,max)}
function stopIdentityMusic(){if(!identityAudio)return;clearInterval(identityAudio.timer);identityAudio.nodes.forEach(node=>{try{node.stop()}catch{}});identityAudio.context.close();identityAudio.button&&(identityAudio.button.textContent=`▶ Ouvir ${musicLabels[identityAudio.theme]}`);identityAudio=null}
function toggleIdentityMusic(theme,button){if(identityAudio){const same=identityAudio.theme===theme;stopIdentityMusic();if(same)return}if(!theme||theme==='silencio')return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext){showToast('Este navegador não oferece reprodução de áudio.','error');return}const context=new AudioContext(),master=context.createGain();master.gain.value=.045;master.connect(context.destination);const notes={aurora:[220,277.18,329.63],fluxo:[174.61,220,261.63],horizonte:[196,246.94,293.66],centelha:[261.63,329.63,392]}[theme];const nodes=notes.map((frequency,index)=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.type=index?'sine':'triangle';oscillator.frequency.value=frequency;gain.gain.value=.45/(index+1);oscillator.connect(gain).connect(master);oscillator.start();return oscillator});let step=0;const timer=setInterval(()=>{step+=1;nodes.forEach((node,index)=>node.frequency.exponentialRampToValueAtTime(notes[(index+step)%notes.length],context.currentTime+1.8))},2400);identityAudio={context,nodes,timer,theme,button};button.textContent='❚❚ Pausar trilha'}

function identityChips(items=[]){return items.map(item=>`<span>${safeText(item)}</span>`).join('')}
function timelineHtml(items=[]){return items.slice(0,5).map(item=>`<article><span>${safeText(item.icon||'✦')}</span><div><strong>${safeText(item.title)}</strong><small>${safeText(item.description||'')} · ${new Date(item.date).toLocaleDateString('pt-BR')}</small></div></article>`).join('')||'<p>Sua história começa com o próximo marco.</p>'}

function ensureIdentityExperience(){
  if(!document.querySelector('#identityExpression')){const section=document.createElement('section');section.id='identityExpression';section.className='identity-expression';document.querySelector('.identity-grid').after(section)}
  if(!document.querySelector('#identityStudioBackdrop')){const modal=document.createElement('div');modal.id='identityStudioBackdrop';modal.className='identity-studio-backdrop';modal.hidden=true;modal.innerHTML=`<section class="identity-studio" role="dialog" aria-modal="true" aria-labelledby="identityStudioTitle"><button class="modal-close" id="identityStudioClose" type="button">×</button><span class="section-kicker">ESTÚDIO DE IDENTIDADE</span><h2 id="identityStudioTitle">Mostre quem você está se tornando.</h2><p>Você controla o que aparece publicamente. Atividades e projetos privados nunca são exibidos automaticamente.</p><form id="identityStudioForm"><div class="identity-studio-grid"><label class="wide">Meu manifesto<textarea id="studioManifesto" maxlength="180" placeholder="Estou me tornando alguém que..."></textarea></label><label>Meus 3 valores<input id="studioValues" maxlength="90" placeholder="Coragem, saúde, presença"><small class="identity-studio-help">Separe por vírgulas.</small></label><label>Interesses<input id="studioInterests" maxlength="150" placeholder="Leitura, corrida, tecnologia"><small class="identity-studio-help">Até 6, separados por vírgulas.</small></label><label>Minha energia hoje<select id="studioEnergy"><option value="serena">🌿 Serena</option><option value="focada">🎯 Focada</option><option value="criativa">✨ Criativa</option><option value="corajosa">🔥 Corajosa</option><option value="equilibrada">☯ Equilibrada</option><option value="celebrando">🎉 Celebrando</option></select></label><label>Destaque atual<input id="studioFocus" maxlength="120" placeholder="Ex.: construindo uma rotina saudável"></label><label>Meu emblema<select id="studioEmblem"><option>✦</option><option>☼</option><option>◇</option><option>⬡</option><option>♛</option><option>∞</option></select></label><label>Trilha da minha Aura<select id="studioMusic"><option value="silencio">Sem trilha</option><option value="aurora">Aurora calma</option><option value="fluxo">Fluxo profundo</option><option value="horizonte">Horizonte leve</option><option value="centelha">Centelha vibrante</option></select></label><label>Estilo do perfil<select id="studioLayout"><option value="essencial">Essencial</option><option value="expressivo">Expressivo</option><option value="jornada">Jornada</option></select></label><div class="wide"><label>Conquistas favoritas</label><div class="identity-achievement-options" id="studioAchievements"></div><small class="identity-studio-help">Escolha até 3. Somente conquistas já recebidas podem ser fixadas.</small></div></div><button class="primary-button identity-studio-save" type="submit">Salvar minha identidade</button></form></section>`;document.body.appendChild(modal);document.querySelector('#identityStudioClose').onclick=closeIdentityStudio;modal.addEventListener('click',event=>{if(event.target===modal)closeIdentityStudio()});document.querySelector('#identityStudioForm').addEventListener('submit',saveIdentityStudio)}
}

function renderOwnIdentity(data){identityData=data;const p=data.profile||{},achievements=data.achievements||[],pinned=achievements.filter(item=>item.pinned);document.querySelector('#identityHonorMark').textContent=p.identity_emblem||'✦';const section=document.querySelector('#identityExpression');section.dataset.layout=p.identity_layout||'essencial';section.innerHTML=`<article class="identity-expression-card"><span class="identity-card-kicker">MEU MANIFESTO</span><h3>${safeText(p.identity_manifesto||'Estou construindo minha identidade, um passo de cada vez.')}</h3><div class="identity-chips">${identityChips(p.identity_values)}</div><div class="identity-chips">${identityChips(p.identity_interests)}</div><div class="identity-controls"><button class="identity-edit" id="openIdentityStudio" type="button">Personalizar identidade</button><button id="shareIdentity" type="button">Compartilhar</button></div></article><article class="identity-expression-card"><span class="identity-card-kicker">MINHA PRESENÇA AGORA</span><div class="identity-now"><div><small>ENERGIA</small><strong>${energyLabels[p.identity_energy]||energyLabels.equilibrada}</strong></div><div><small>EM DESTAQUE</small><strong>${safeText(p.identity_focus||'Escolha o que deseja destacar.')}</strong></div><div><small>CONQUISTAS FAVORITAS</small><strong>${pinned.map(item=>`${safeText(item.icon)} ${safeText(item.name)}`).join(' · ')||'Nenhuma fixada'}</strong></div></div>${p.identity_music&&p.identity_music!=='silencio'?`<button class="public-music-button" id="ownMusicButton" type="button">▶ Ouvir ${musicLabels[p.identity_music]}</button>`:''}</article><article class="identity-expression-card wide"><span class="identity-card-kicker">LINHA DO TEMPO</span><div class="identity-timeline">${timelineHtml(data.milestones)}</div></article>`;document.querySelector('#openIdentityStudio').onclick=openIdentityStudio;document.querySelector('#shareIdentity').onclick=shareIdentity;document.querySelector('#ownMusicButton')?.addEventListener('click',event=>toggleIdentityMusic(p.identity_music,event.currentTarget))}

async function openIdentityStudio(){if(!identityData)return;const p=identityData.profile;document.querySelector('#studioManifesto').value=p.identity_manifesto||'';document.querySelector('#studioValues').value=(p.identity_values||[]).join(', ');document.querySelector('#studioInterests').value=(p.identity_interests||[]).join(', ');document.querySelector('#studioEnergy').value=p.identity_energy||'equilibrada';document.querySelector('#studioFocus').value=p.identity_focus||'';document.querySelector('#studioEmblem').value=p.identity_emblem||'✦';document.querySelector('#studioMusic').value=p.identity_music||'silencio';document.querySelector('#studioLayout').value=p.identity_layout||'essencial';document.querySelector('#studioAchievements').innerHTML=(identityData.achievements||[]).map(item=>`<label><input type="checkbox" value="${item.id}" ${item.pinned?'checked':''}><span>${safeText(item.icon)} ${safeText(item.name)}</span></label>`).join('')||'<small>Conquiste seu primeiro troféu para fixá-lo aqui.</small>';document.querySelector('#identityStudioBackdrop').hidden=false;document.body.style.overflow='hidden'}
function closeIdentityStudio(){document.querySelector('#identityStudioBackdrop').hidden=true;document.body.style.overflow=''}
async function saveIdentityStudio(event){event.preventDefault();const pinned=[...document.querySelectorAll('#studioAchievements input:checked')].slice(0,3).map(input=>input.value);const updates={identity_manifesto:document.querySelector('#studioManifesto').value.trim()||null,identity_values:identityList(document.querySelector('#studioValues').value,3),identity_interests:identityList(document.querySelector('#studioInterests').value,6),identity_energy:document.querySelector('#studioEnergy').value,identity_focus:document.querySelector('#studioFocus').value.trim()||null,identity_emblem:document.querySelector('#studioEmblem').value,identity_music:document.querySelector('#studioMusic').value,identity_layout:document.querySelector('#studioLayout').value,pinned_achievement_ids:pinned,updated_at:new Date().toISOString()};const button=event.submitter;button.disabled=true;const{error}=await window.auraSupabase.from('profiles').update(updates).eq('id',window.AURA_SESSION.user.id);button.disabled=false;if(error){showToast(error.message.includes('identity_')?'Execute a migration 018 no Supabase para ativar o Estúdio de Identidade.':error.message,'error','Não foi possível salvar');return}closeIdentityStudio();showToast('Seu perfil agora expressa melhor quem você é.','success','Identidade atualizada');await loadIdentityProfile()}

async function shareIdentity(){const url=`${location.origin}${location.pathname}?profile=${window.AURA_SESSION.user.id}`;const payload={title:`Identidade Aura de ${identityData.profile.full_name}`,text:identityData.profile.identity_manifesto||'Conheça minha evolução na Aura 67.',url};if(navigator.share){await navigator.share(payload).catch(()=>{})}else{await navigator.clipboard.writeText(url);showToast('Link do perfil copiado.','success','Pronto para compartilhar')}}
function renderPublicIdentity(data){const p=data.profile||{},pinned=(data.achievements||[]).filter(item=>item.pinned),avatar=document.querySelector('#publicProfileAvatar'),avatarUrl=p.avatar_url?mediaUrl(p.avatar_url):'';avatar.className=`public-profile-avatar ${honorFrameClass(p.honor_points||0)}`;avatar.style.backgroundImage=avatarUrl?`url('${avatarUrl}')`:'';avatar.textContent=avatarUrl?'':initials(p.full_name||'Aura');let extra=document.querySelector('#publicIdentityExtra');if(!extra){extra=document.createElement('div');extra.id='publicIdentityExtra';extra.className='public-identity-extra';document.querySelector('.profile-fireworks').before(extra)}extra.innerHTML=`${p.identity_manifesto?`<p class="public-identity-manifesto">“${safeText(p.identity_manifesto)}”</p>`:''}<div class="public-identity-row">${identityChips(p.identity_values)}${identityChips(p.identity_interests)}</div><div class="public-identity-row"><span>${energyLabels[p.identity_energy]||energyLabels.equilibrada}</span>${p.identity_focus?`<span>↗ ${safeText(p.identity_focus)}</span>`:''}${pinned.map(item=>`<span>${safeText(item.icon)} ${safeText(item.name)}</span>`).join('')}</div>${p.identity_music&&p.identity_music!=='silencio'?`<button class="public-music-button" id="publicMusicButton" type="button">▶ Ouvir ${musicLabels[p.identity_music]}</button>`:''}<div class="public-mini-timeline">${(data.milestones||[]).slice(0,2).map(item=>`${safeText(item.icon)} ${safeText(item.title)}`).join(' · ')}</div>`;document.querySelector('#publicMusicButton')?.addEventListener('click',event=>toggleIdentityMusic(p.identity_music,event.currentTarget))}

ensureIdentityExperience();
const baseLoadIdentityProfile=loadIdentityProfile;
loadIdentityProfile=async function(){await baseLoadIdentityProfile();const{data,error}=await window.auraSupabase.rpc('public_profile_identity',{p_profile_id:window.AURA_SESSION.user.id});if(error){document.querySelector('#identityExpression').innerHTML='<article class="identity-expression-card"><h3>Estúdio de Identidade</h3><p>Execute a migration 018 no Supabase para ativar manifesto, valores, música e destaques.</p></article>';return}renderOwnIdentity(data)};
const baseOpenPublicProfile=openPublicProfile;
openPublicProfile=async function(person){stopIdentityMusic();person={...person,id:person.profile_id||person.user_id||person.id};await baseOpenPublicProfile(person);const{data}=await window.auraSupabase.rpc('public_profile_identity',{p_profile_id:person.id});if(data)renderPublicIdentity(data)};
document.querySelector('#publicProfileClose').addEventListener('click',stopIdentityMusic);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopIdentityMusic()});
document.addEventListener('aura:session-ready',async()=>{const profileId=new URLSearchParams(location.search).get('profile');if(!profileId)return;const{data}=await window.auraSupabase.from('profiles').select('id,full_name,username,bio,avatar_url,cover_url,theme_color,aura_points,member_number').eq('id',profileId).maybeSingle();if(data)openPublicProfile(data)});
if(window.AURA_SESSION){setTimeout(async()=>{const profileId=new URLSearchParams(location.search).get('profile');if(!profileId)return;const{data}=await window.auraSupabase.from('profiles').select('id,full_name,username,bio,avatar_url,cover_url,theme_color,aura_points,member_number').eq('id',profileId).maybeSingle();if(data)openPublicProfile(data)},0)}
