let pendingAuraMoment=null;let auraMomentProfiles=new Map();
const momentEsc=(value='')=>{const node=document.createElement('span');node.textContent=value;return node.innerHTML};
const momentInitials=(name='Aura')=>name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
const momentTime=value=>new Intl.RelativeTimeFormat('pt-BR',{numeric:'auto'}).format(-Math.max(0,Math.round((Date.now()-new Date(value))/86400000)),'day');
const momentDimension={acao:'Ação',constancia:'Constância',coragem:'Coragem',impacto:'Impacto'};
function openAuraMomentShare(sourceType,sourceId,title,icon='✦'){pendingAuraMoment={sourceType,sourceId:String(sourceId)};document.querySelector('#momentShareIcon').textContent=icon;document.querySelector('#momentShareTitle').textContent='Compartilhar este Momento?';document.querySelector('#momentShareDescription').textContent=title;document.querySelector('#momentShareBackdrop').hidden=false;document.body.style.overflow='hidden';document.querySelector('#momentShareConfirm').focus()}
function closeAuraMomentShare(){document.querySelector('#momentShareBackdrop').hidden=true;document.body.style.overflow='';pendingAuraMoment=null}
function renderAuraMoments(rows){const feed=document.querySelector('#momentsFeed');auraMomentProfiles=new Map(rows.map(row=>[row.user_id,row]));feed.innerHTML=rows.length?rows.map(row=>{const color=/^#[0-9a-f]{6}$/i.test(row.theme_color||'')?row.theme_color:'#7657ec',avatar=row.avatar_url&&typeof mediaUrl==='function'?mediaUrl(row.avatar_url):'',own=row.user_id===window.AURA_SESSION.user.id;return `<article class="moment-card" data-moment-id="${row.id}" style="--moment-color:${color};--moment-soft:${color}1f"><div class="moment-person" data-moment-profile="${row.user_id}"><span class="moment-avatar">${avatar?`<img src="${momentEsc(avatar)}" alt="">`:momentEsc(momentInitials(row.full_name))}</span><span><strong>${momentEsc(row.full_name)}</strong><small>@${momentEsc(row.username||'perfil-aura')} · ${momentTime(row.created_at)}</small></span><b class="moment-badge">${momentDimension[row.dimension]||'Aura'}</b></div><div class="moment-main"><span class="moment-icon">${momentEsc(row.icon)}</span><div><h3>${momentEsc(row.title)}</h3><small>${row.verification==='comprovada'?'✓ Comprovação aprovada':row.verification==='sistema'?'✓ Confirmado pelo sistema':'Registro pessoal'} · +${row.points_snapshot} Aura</small></div></div><div class="moment-actions"><button class="moment-fire ${row.viewer_fired?'active':''}" type="button">🎆 <span>${row.fire_count||0}</span> Fogos</button>${own?'<button class="moment-delete" type="button">Excluir Momento</button>':''}</div></article>`}).join(''):'<div class="moment-empty"><strong>O primeiro Momento pode ser seu.</strong><small>Conclua uma ação ou projeto e escolha compartilhá-lo com a comunidade.</small></div>'}
async function loadAuraMoments(){if(!window.AURA_SESSION)return;const{data,error}=await window.auraSupabase.rpc('get_aura_moments',{p_limit:20});if(error){document.querySelector('#momentsFeed').innerHTML=`<div class="moment-empty"><strong>Momentos de Aura ainda não estão ativos.</strong><small>Execute a migration 023 no Supabase.</small></div>`;return}renderAuraMoments(data||[])}
document.querySelector('#momentShareCancel').addEventListener('click',closeAuraMomentShare);document.querySelector('#momentShareLater').addEventListener('click',closeAuraMomentShare);document.querySelector('#momentShareBackdrop').addEventListener('click',event=>{if(event.target.id==='momentShareBackdrop')closeAuraMomentShare()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!document.querySelector('#momentShareBackdrop').hidden)closeAuraMomentShare()});
document.querySelector('#momentShareConfirm').addEventListener('click',async event=>{if(!pendingAuraMoment)return;const button=event.currentTarget;button.disabled=true;const{error}=await window.auraSupabase.rpc('publish_aura_moment',{p_source_type:pendingAuraMoment.sourceType,p_source_id:pendingAuraMoment.sourceId});button.disabled=false;if(error){showToast(/publish_aura_moment|schema cache/i.test(error.message)?'Execute a migration 023 no Supabase para ativar Momentos.':error.message,'error','Momento não publicado');return}closeAuraMomentShare();showToast('Sua conquista agora pode inspirar outras pessoas.','success','Momento publicado');loadAuraMoments()});
document.querySelector('#momentsFeed').addEventListener('click',async event=>{const card=event.target.closest('[data-moment-id]');if(!card)return;if(event.target.closest('[data-moment-profile]')){const person=auraMomentProfiles.get(event.target.closest('[data-moment-profile]').dataset.momentProfile);if(person&&typeof openPublicProfile==='function')openPublicProfile(person);return}const fire=event.target.closest('.moment-fire');if(fire){fire.disabled=true;const{data,error}=await window.auraSupabase.rpc('toggle_aura_moment_fire',{p_moment_id:card.dataset.momentId});fire.disabled=false;if(error)return showToast(error.message,'error');fire.classList.toggle('active',data.active);fire.querySelector('span').textContent=data.fire_count;if(data.own_moment)return showToast('Os Fogos do seu próprio Momento não entram na contagem.','info','Momento próprio');if(data.active&&typeof launchProfileFireworks==='function')launchProfileFireworks();return}if(event.target.closest('.moment-delete')){const remove=event.target.closest('.moment-delete');remove.disabled=true;const{data,error}=await window.auraSupabase.rpc('delete_aura_moment',{p_moment_id:card.dataset.momentId});remove.disabled=false;if(error)return showToast(error.message,'error','Não foi possível excluir');if(data){card.remove();showToast('O Momento foi removido do feed.','success','Momento excluído')}}});
document.addEventListener('aura:session-ready',loadAuraMoments);if(window.AURA_SESSION)loadAuraMoments();
