let realRankingProfiles=[];
function rankingEscape(value=''){const node=document.createElement('span');node.textContent=value;return node.innerHTML;}
function rankingInitials(name='Pessoa Aura'){return name.split(/\s+/).slice(0,2).map((part)=>part[0]).join('').toUpperCase();}
function rankingAvatar(profile,classes){const url=profile.avatar_url&&typeof mediaUrl==='function'?mediaUrl(profile.avatar_url):'';return `<span class="${classes}"${url?` style="background-image:url('${url}')"`:''}>${url?'':rankingEscape(rankingInitials(profile.full_name))}</span>`;}
function isCurrentRankingUser(profile){return profile.id===window.AURA_SESSION?.user.id;}
function rankingClass(profile){return typeof classFor==='function'?classFor(profile.aura_points||0):{name:'Centelha',icon:'✦'};}
function renderRealPodium(profiles){const podium=document.querySelector('#realPodium');if(!profiles.length){podium.classList.add('podium-empty');podium.innerHTML='<div class="ranking-empty"><span>✦</span><strong>O ranking está esperando seu primeiro membro.</strong></div>';return;}podium.classList.remove('podium-empty');const top=profiles.slice(0,3);const order=top.length===3?[top[1],top[0],top[2]]:top;podium.dataset.count=String(top.length);podium.innerHTML=order.map((profile)=>{const position=profiles.indexOf(profile)+1;const place=position===1?'first-place':position===2?'second-place':'third-place';const level=rankingClass(profile);return `<article class="podium-card ${place} ${isCurrentRankingUser(profile)?'is-you':''}" data-profile-id="${profile.id}">${position===1?'<span class="crown">♛</span>':''}<span class="podium-rank">${position}</span>${rankingAvatar(profile,'podium-avatar')}<strong>${rankingEscape(profile.full_name)}${isCurrentRankingUser(profile)?' <b>Você</b>':''}</strong><small>${(profile.aura_points||0).toLocaleString('pt-BR')} pontos</small><span class="streak">${level.icon} ${level.name}</span></article>`}).join('');podium.querySelectorAll('[data-profile-id]').forEach((card)=>card.addEventListener('click',()=>{const profile=profiles.find((item)=>item.id===card.dataset.profileId);if(profile&&typeof openPublicProfile==='function')openPublicProfile(profile);}));}
function renderRealLeaderboard(profiles){const board=document.querySelector('#leaderboard');document.querySelector('#realParticipants').textContent=`${profiles.length} ${profiles.length===1?'participante':'participantes'}`;if(!profiles.length){board.innerHTML='<div class="ranking-empty"><strong>Nenhuma pessoa cadastrada.</strong></div>';return;}board.innerHTML=profiles.map((profile,index)=>{const level=rankingClass(profile);const positionClass=index===0?'gold':index===1?'silver':index===2?'bronze':'';return `<div class="leader-row ${isCurrentRankingUser(profile)?'current-user':''}" data-profile-id="${profile.id}"><span class="position ${positionClass}">${index+1}</span>${rankingAvatar(profile,'member-avatar')}<span class="member"><strong>${rankingEscape(profile.full_name)}${isCurrentRankingUser(profile)?' <b>Você</b>':''}</strong><small>${level.icon} ${level.name}${profile.username?` · @${rankingEscape(profile.username)}`:''}</small></span><span class="movement same">—</span><span class="score"><strong>${(profile.aura_points||0).toLocaleString('pt-BR')}</strong><small>pontos</small></span></div>`}).join('');board.querySelectorAll('[data-profile-id]').forEach((row)=>row.addEventListener('click',()=>{const profile=profiles.find((item)=>item.id===row.dataset.profileId);if(profile&&typeof openPublicProfile==='function')openPublicProfile(profile);}));const userIndex=profiles.findIndex(isCurrentRankingUser);const gapElement=document.querySelector('#pointsGap');const chaseCopy=document.querySelector('.chase-card>small');if(userIndex===0){gapElement.textContent='Você está no topo!';chaseCopy.textContent=profiles.length===1?'Convide pessoas para começar a disputa':'Continue defendendo sua posição';}else if(userIndex>0){const gap=(profiles[userIndex-1].aura_points||0)-(profiles[userIndex].aura_points||0);gapElement.textContent=`${gap.toLocaleString('pt-BR')} pontos`;chaseCopy.textContent=`para alcançar o ${userIndex}º lugar`;}else{gapElement.textContent='Complete sua Jornada';chaseCopy.textContent='para entrar na classificação';}}
async function loadRealRanking(){if(!window.auraSupabase||!window.AURA_SESSION)return;const{data,error}=await window.auraSupabase.from('profiles').select('id,full_name,username,bio,avatar_url,cover_url,theme_color,aura_points,member_number').order('aura_points',{ascending:false}).order('created_at',{ascending:true}).limit(100);if(error){document.querySelector('#leaderboard').innerHTML=`<div class="ranking-empty">Não foi possível carregar o ranking: ${rankingEscape(error.message)}</div>`;return;}realRankingProfiles=data||[];renderRealPodium(realRankingProfiles);renderRealLeaderboard(realRankingProfiles);}
document.addEventListener('aura:session-ready',loadRealRanking);if(window.AURA_SESSION)loadRealRanking();
