const reminderBackdrop = document.querySelector('#reminderBackdrop');
const reminderDefaults = { enabled:false,wake_time:'07:00',sleep_time:'22:30',max_per_day:4,categories:['water','food','movement','rest','focus'],weekdays:[1,2,3,4,5,6,7],personalized:true };
const AURA_VAPID_PUBLIC_KEY='BMXwM7ia_Tk2XfCDKLE5SrJ4i6MzxDYQX4hTWUjJdB3R7PSlLNQ_Q0mfAG3quOdtp4vBot-SQjo5B3ZYc3i_kAc';
const auraQuickActions=[
  'Beba um copo de água agora. Seu corpo agradece esse pequeno cuidado. 💧',
  'Levante-se e alongue braços, costas e pescoço por 2 minutos. 🙆',
  'Respire fundo 5 vezes, soltando o ar mais devagar do que puxou. 🌿',
  'Afaste os olhos da tela e observe algo distante por 30 segundos. 👀',
  'Organize por 3 minutos apenas o espaço que está ao seu alcance. ✨',
  'Escolha uma tarefa pequena e faça só o primeiro passo agora. 🎯',
  'Caminhe um pouco, mesmo que seja apenas pelo cômodo onde você está. 🚶',
  'Pense em uma coisa boa deste dia e registre em uma frase. 💛'
];
const pushPanel=document.createElement('section');pushPanel.className='push-panel';pushPanel.innerHTML='<span>🔔</span><div><strong>Notificações neste dispositivo</strong><small id="pushStatus">Verificando compatibilidade…</small></div><button id="enablePushButton" type="button">Ativar</button>';
document.querySelector('.reminder-save').before(pushPanel);

function timeValue(value,fallback){return String(value||fallback).slice(0,5)}
function setCheckedValues(name,values){document.querySelectorAll(`[name="${name}"]`).forEach((input)=>{input.checked=values.includes(name==='reminderWeekday'?Number(input.value):input.value)})}
function fillReminderForm(data={}){const value={...reminderDefaults,...data};document.querySelector('#reminderEnabled').checked=value.enabled;document.querySelector('#reminderWake').value=timeValue(value.wake_time,'07:00');document.querySelector('#reminderSleep').value=timeValue(value.sleep_time,'22:30');document.querySelector('#reminderFrequency').value=value.max_per_day;document.querySelector('#reminderFrequencyValue').textContent=value.max_per_day;document.querySelector('#reminderPersonalized').checked=value.personalized;setCheckedValues('reminderCategory',value.categories||reminderDefaults.categories);setCheckedValues('reminderWeekday',value.weekdays||reminderDefaults.weekdays)}
async function loadReminderPreferences(){const message=document.querySelector('#reminderMessage');message.textContent='Carregando preferências…';const{data,error}=await window.auraSupabase.from('reminder_preferences').select('*').eq('user_id',window.AURA_SESSION.user.id).maybeSingle();if(error){message.style.color='#b44';message.textContent='Execute a migration 008 para ativar esta central.';fillReminderForm();return}fillReminderForm(data||reminderDefaults);message.textContent=''}
function openReminderCenter(){setAccountMenu(false);reminderBackdrop.hidden=false;document.body.style.overflow='hidden';loadReminderPreferences();refreshPushStatus()}
function closeReminderCenter(){reminderBackdrop.hidden=true;document.body.style.overflow=''}
function urlBase64ToUint8Array(value){const padding='='.repeat((4-value.length%4)%4);const base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map((char)=>char.charCodeAt(0)))}
async function refreshPushStatus(){const status=document.querySelector('#pushStatus');const button=document.querySelector('#enablePushButton');if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){status.textContent='Este navegador não oferece Web Push.';button.disabled=true;return}if(Notification.permission==='denied'){status.textContent='Permissão bloqueada nas configurações do celular.';button.disabled=true;return}const registration=await navigator.serviceWorker.ready;const subscription=await registration.pushManager.getSubscription();status.textContent=subscription?'Ativas neste dispositivo.':'Toque em Ativar para permitir os lembretes.';button.textContent=subscription?'Receber uma ação':'Ativar';button.dataset.subscribed=String(Boolean(subscription))}
async function registerPushSubscription(json){const base={p_endpoint:json.endpoint,p_p256dh:json.keys.p256dh,p_user_agent:navigator.userAgent};let result=await window.auraSupabase.rpc('register_push_subscription',{...base,p_auth_key:json.keys.auth});if(result.error?.code==='PGRST202'||result.error?.message?.includes('p_auth_key'))result=await window.auraSupabase.rpc('register_push_subscription',{...base,p_auth:json.keys.auth});return result}
function randomQuickAction(){return auraQuickActions[Math.floor(Math.random()*auraQuickActions.length)]}
async function showQuickAction(registration,tag='aura-action'){await registration.showNotification('Uma pequena ação para agora ✦',{body:randomQuickAction(),icon:'assets/icons/icon.svg',badge:'assets/icons/icon.svg',tag,data:{url:'app.html#habits'}})}
async function enablePush(){const button=document.querySelector('#enablePushButton');const status=document.querySelector('#pushStatus');button.disabled=true;try{const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(subscription){await showQuickAction(registration);status.textContent='Uma ação foi enviada para você.';return}const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('A permissão de notificações não foi concedida.');subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(AURA_VAPID_PUBLIC_KEY)});const json=subscription.toJSON();const{error}=await registerPushSubscription(json);if(error){await subscription.unsubscribe();throw error}await showQuickAction(registration,'aura-welcome');await refreshPushStatus()}catch(error){status.textContent=error.message}finally{button.disabled=false}}
document.querySelector('#openRemindersButton').addEventListener('click',openReminderCenter);
document.querySelector('#enablePushButton').addEventListener('click',enablePush);
document.querySelector('#reminderClose').addEventListener('click',closeReminderCenter);
reminderBackdrop.addEventListener('click',(event)=>{if(event.target===reminderBackdrop)closeReminderCenter()});
document.querySelector('#reminderFrequency').addEventListener('input',(event)=>{document.querySelector('#reminderFrequencyValue').textContent=event.target.value});
document.querySelector('#reminderForm').addEventListener('submit',async(event)=>{event.preventDefault();const message=document.querySelector('#reminderMessage');const categories=[...document.querySelectorAll('[name="reminderCategory"]:checked')].map((input)=>input.value);const weekdays=[...document.querySelectorAll('[name="reminderWeekday"]:checked')].map((input)=>Number(input.value));if(!categories.length||!weekdays.length){message.style.color='#b44';message.textContent='Escolha pelo menos uma categoria e um dia da semana.';return}const payload={user_id:window.AURA_SESSION.user.id,enabled:document.querySelector('#reminderEnabled').checked,wake_time:document.querySelector('#reminderWake').value,sleep_time:document.querySelector('#reminderSleep').value,max_per_day:Number(document.querySelector('#reminderFrequency').value),categories,weekdays,personalized:document.querySelector('#reminderPersonalized').checked,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo',updated_at:new Date().toISOString()};message.style.color='';message.textContent='Salvando preferências…';const{error}=await window.auraSupabase.from('reminder_preferences').upsert(payload,{onConflict:'user_id'});if(error){message.style.color='#b44';message.textContent=error.message;return}message.style.color='#318361';message.textContent=payload.enabled?'Companheiro Aura configurado. As notificações serão ativadas na próxima etapa.':'Preferências salvas. Os lembretes permanecem pausados.'});
