const reminderBackdrop = document.querySelector('#reminderBackdrop');
const reminderDefaults = { enabled:false,wake_time:'07:00',sleep_time:'22:30',max_per_day:4,categories:['water','food','movement','rest','focus'],weekdays:[1,2,3,4,5,6,7],personalized:true };

function timeValue(value,fallback){return String(value||fallback).slice(0,5)}
function setCheckedValues(name,values){document.querySelectorAll(`[name="${name}"]`).forEach((input)=>{input.checked=values.includes(name==='reminderWeekday'?Number(input.value):input.value)})}
function fillReminderForm(data={}){const value={...reminderDefaults,...data};document.querySelector('#reminderEnabled').checked=value.enabled;document.querySelector('#reminderWake').value=timeValue(value.wake_time,'07:00');document.querySelector('#reminderSleep').value=timeValue(value.sleep_time,'22:30');document.querySelector('#reminderFrequency').value=value.max_per_day;document.querySelector('#reminderFrequencyValue').textContent=value.max_per_day;document.querySelector('#reminderPersonalized').checked=value.personalized;setCheckedValues('reminderCategory',value.categories||reminderDefaults.categories);setCheckedValues('reminderWeekday',value.weekdays||reminderDefaults.weekdays)}
async function loadReminderPreferences(){const message=document.querySelector('#reminderMessage');message.textContent='Carregando preferências…';const{data,error}=await window.auraSupabase.from('reminder_preferences').select('*').eq('user_id',window.AURA_SESSION.user.id).maybeSingle();if(error){message.style.color='#b44';message.textContent='Execute a migration 008 para ativar esta central.';fillReminderForm();return}fillReminderForm(data||reminderDefaults);message.textContent=''}
function openReminderCenter(){setAccountMenu(false);reminderBackdrop.hidden=false;document.body.style.overflow='hidden';loadReminderPreferences()}
function closeReminderCenter(){reminderBackdrop.hidden=true;document.body.style.overflow=''}
document.querySelector('#openRemindersButton').addEventListener('click',openReminderCenter);
document.querySelector('#reminderClose').addEventListener('click',closeReminderCenter);
reminderBackdrop.addEventListener('click',(event)=>{if(event.target===reminderBackdrop)closeReminderCenter()});
document.querySelector('#reminderFrequency').addEventListener('input',(event)=>{document.querySelector('#reminderFrequencyValue').textContent=event.target.value});
document.querySelector('#reminderForm').addEventListener('submit',async(event)=>{event.preventDefault();const message=document.querySelector('#reminderMessage');const categories=[...document.querySelectorAll('[name="reminderCategory"]:checked')].map((input)=>input.value);const weekdays=[...document.querySelectorAll('[name="reminderWeekday"]:checked')].map((input)=>Number(input.value));if(!categories.length||!weekdays.length){message.style.color='#b44';message.textContent='Escolha pelo menos uma categoria e um dia da semana.';return}const payload={user_id:window.AURA_SESSION.user.id,enabled:document.querySelector('#reminderEnabled').checked,wake_time:document.querySelector('#reminderWake').value,sleep_time:document.querySelector('#reminderSleep').value,max_per_day:Number(document.querySelector('#reminderFrequency').value),categories,weekdays,personalized:document.querySelector('#reminderPersonalized').checked,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo',updated_at:new Date().toISOString()};message.style.color='';message.textContent='Salvando preferências…';const{error}=await window.auraSupabase.from('reminder_preferences').upsert(payload,{onConflict:'user_id'});if(error){message.style.color='#b44';message.textContent=error.message;return}message.style.color='#318361';message.textContent=payload.enabled?'Companheiro Aura configurado. As notificações serão ativadas na próxima etapa.':'Preferências salvas. Os lembretes permanecem pausados.'});
